### ISSUE TITLE
[bounty] dat-ecosystem website

### ISSUE THREAD

**Issue by serapath** [playproject-io/contracting#1]
# `@todo` :hammer_and_wrench:
* [ ] **tasks here are to be done by our team. applicants please skip and read `@info` section**
  * [x] make `application form`
    * [x] #2
  * [x] make `trial phase roadmap`
    * [ ] #3
  * [x] make `first gig roadmap draft`
    * [ ] #4
  * [x] `publish gig` for candidates to apply

---
 
# `@info` :point_down:

## :mage_woman: who are we?
<details>
<summary>

The https://playproject.io team is looking to work with independent web ui/ux collaborators(s)

**>> click here to expand more details**
</summary>

1. Everything we do is 100% open source and can be (re)used by anyone in the future.
2. Everyone in our team is independent, self employed and we connect professionally on social media to our global community
3. We give talks at online and physical conferences and support contractors to present their work.
4. Our current project **datodot** is a bleeding edge blockchain project.
5. When our blockchain launches, there will be tokens for everyone who helped along the way.

we are supported by https://web3.foundation/ and https://polkadot.network/
</details>

## :telescope: who we are looking for?
<details>
<summary>

We are looking for self employed/freelancing web UI/UX designers who know how to use adobe/figma or similar tools, who can write raw CSS to create custom css grid or flexbox layouts, who can quickly hand code responsiveness, who know how to use css properties to make custom themes and  who are familiar with the latest CSS features, like "container queries" for web components and more.

**>> click here to expand more details**
</summary>

---

1. **expert CSS**
    * animations/transitions/transformations during user interaction
    * responsiveness + feature queries + aspect ratio
    * latest css features (e.g. contain queries, containment, @supports)
    * experience using css properties for deriving colors and other things
    * experience with custom css themes for web components
    * no CSS frameworks
    * custom complex css subgrid/flexbox layouts
    * bonus: knowledge of doing "shadow dom" styling (e.g. slot & :root {} selectors)
    * bonus: refine svg graphics and icons and style them
2. **expert Adobe CS/XD, Figma (or similar tools)**
    * make and change wireframes UI/UX for complex apps/website and UI components
    * create style and theme for apps and UI components based on mood boards
    * create custom **icon sets** or **vector graphics** and/or logos
    * build style guides to show components with theme in different states
3. **experience with UX + product development**
    * tweak existing UI/UX and make components and user flows more user friendly and lean 
    * research/invent/design new custom UI components based on requirements
    * help us improve the UX of our websites/apps to make them more user friendly
    * come up with new unique components to communicate and enable new unique features

</details>

| gig                              |  `make wireframes + themes for a website`                            | 
|-----------------------------:|:--------------------------------------------------------------------------------|
| application deadline   |  `Friday April 22 2022 by 23:00(UTC-0)`                                           | 
| profile                         | `freelance ux/ui web design`                                                   | 
| budget                        | `200 USD/week` for full time work (`40h/week at 5USD/h`)   | 
| duration                      | 1. `trial phase: 48 hours`   2. `gig phase: 4-8 weeks`           | 

We will notify selected candidate(s) on Monday `April 25 2022` to start the paid trial phase. After the trial phase is completed, we notify the collaborator(s) to start working on the paid gig.

*If you have any questions, please leave a comment*

**Comment by serapath** [comment]
@CodeLawd
@Hornet004
@Helenphina

alright.
everyting is ready for you to start the trial phase project.
Its a lot of instructions, so please read everything carefully :-)

I will be busy with my work during the entire day, but in the late afternoon, i will check and respond to questions and give feedback.

The 48hours of the trial phase start in the afternoon.
So the trial phase ends the day after tomorrow in the afternoon/evening.
