### ISSUE TITLE
trial phase task for @Helenphina

### ISSUE THREAD

**Issue by serapath** [playproject-io/contracting#11]
## `@todo`
* [x] make a very detailed project plan for the new dat-ecosystem website using our github issues based project management methods
  * `@input` :package: [`dat-ecosystem project screencast`](https://share.vidyard.com/watch/66BS2ddz4XHg8zvShmuJ2e?) from #3
  * `@input` :package: [`github issue management system`](https://share.vidyard.com/watch/ssnP1kGuw5WdWuwJywRrho?) from #3
  * `@input` :package: [`example project screencast "wizardamigos"`](https://share.vidyard.com/watch/V2ThxmUj6tEb3Z8tmBxh9o?) from #3
  * `@input` :package: [`example project screencast "datdot-ui"`](https://share.vidyard.com/watch/paHEaJmW4v63kpcvLyGHyC?) from #3
  * `@input` :package: [`little checklist and summary`](https://share.vidyard.com/watch/Gn99BGZU4JbPHZuYwYxzmV?) from #3
  * [x] study all the input materials provided
  * [x] create a new "roadmapping" issue called **`"new dat-ecosystem website project plan"`** and post it in the comments below as your first worklog
    * `@output` :question: `new dat-ecosystem website project plan issue`
  * [x] create a detailed project plan from A to Z about the new dat-ecosystem website
    * [x] keep in mind the project should last 4-8 weeks
    * [x] include a high level list of tasks that can be issues itself to outline the important parts of the project
    * [x] include all inputs listed above and whatever else you find important as inputs in your main project issue or any sub issue
    * [x] create more sub tasks and sub issues to get to all tasks that will need to be executed to finish the entire project
    * [x] write the expected input links to documents and expected output documents for each tasks or sub task in your project plan
    * [x] link all planned outputs of the earlier tasks in your plan as inputs of the later tasks in your project structure
    * [x] add for each task additional information or links or inspiration or anything in the issues `@info` section in each task issue or sub task issue you made
    * [x] write down/adapt/modify/update the list of final output(s) for your plan plan in a comment here below in this issue
  * `@output` :question: `website UI/UX specification & wireframes`
  * `@output` :question: `dat-ecosystem design system`
  * `@output` :question: `list of re-usable web components`
  * `@output` :question: `implemented website`
  * `@output` :question: `link to one or multiple final screencasts (each 3-5 minutes max) where the candidate walks us through the entire project plan`

---

## `@info`

all details of the dat-ecosystem project can be found here
* #3 in the `@info` section

### questions
Please ask us anything you don't understand or need to know about the project.
To find out how exactly, please watch the `@input` tagged explanatory video linked above
* in short:
  * Just post a `worklog` comment and write or post a screencast to show us the materials
  * or anything you want to ask and we will quickly post a feedback comment to provide answers.
  * How this works is descibed in your personal issue in the input screencasts that explain it further.

### task
The "end users" of the website will be the members of the dat ecosystem consortium
and everyone who founds and build their own project on top of the same software stack,
which at the moment is mainly https://hypercore-protocol.org and we can answer all questions on behalf of all other "end users".

**Based on the many resources above which you can use as inputs How would you structure the website to somehow integrate the long history into the new website?**
* Please feel free to edit your issue and make more tasks and todos and move some of the inputs under todos where they belong
* If you can group inputs based on the part of the website that will deal with them, that might make it better.
* You might also want to create new issues and link them as todos so some inputs can be handled in that sub issue.
* Everything that helps to keep things more neat is great :-)
* to repeat it again - the technique how to do all that is described in the `@input` video above

**Comment by Helenphina** [comment]
## worklog `2022.04.28`
* `@output` ❓ #17 
   * `@output`❓`project brief slide deck`
   * `@output`❓`Link to stakeholders answers`
   * `@output`❓`Link to users answers`
   * `@output`❓`Link to user persona`
   * `@output`❓` Link to empathy map`
   * `@output`❓`Link to journey map`
   * `@output`❓`Link to user flow chart`
   * `@output`❓`Colors`
   * `@output`❓`grids`
   * `@output`❓`typography`
   * `@output`❓`icons`
   * `@output`❓`buttons`
   * `@output`❓`textholder`
   * `@output`❓`link to site map`
   * `@output`❓`link to sketches`
   * `@output`❓`link to wireframes`
   * `@output`❓`link to high fidelity design`
   * `@output`❓🏁` a working high fidelity Design (New dat ecosystem website)`
   * `@output`❓🏁`a 3-5 minutes video Screencast`

**Comment by serapath** [comment]
> @Helenphina 
> **worklog `2022.04.28`**
> * `@output` ❓ : #17

**Comment by serapath** [comment]
merged into #49
