### ISSUE TITLE
Information Architecture

### ISSUE THREAD

**Issue by Hornet004** [playproject-io/contracting#14]
## `@todo`
- [ ] Information Architecture
  - [ ]  Draw out inspiration for concept from #3 
      - `@input` :package: [current dat-ecosystem website: https://dat-ecosystem.org](https://dat-ecosystem.org) `from` #3 
     - `@input` :factory:  [ Dat ecosystem as a garden](https://github.com/dat-ecosystem/organization/blob/main/README.md) `from` #3
     - `@input` :factory:  [ dat-ecosystem as a garden Vision/Mission](https://hackmd.io/6T6MwxU8SSefMiQsusFVvg) `from` #3
     - `@input` :factory:  [ history info 2](https://hackmd.io/cuolp56RRkmMNqr_6fIW1A) `from` #3
     - `@input` :factory:  [ history info 3](https://dat.foundation/about/history/) `from` #3
     - `@input` :factory:  [ usable website section for dat-ecosystem as a garden](https://user-images.githubusercontent.com/1076427/145653389-814d54e1-148e-4e47-af38-0e34aceba2d9.png) `from` #3
     - `@input` :factory:  [ Joining Rules](https://hackmd.io/5zL2Qt4_Sv6-_YgY8rJspg) `from` #3
     - `@input` :factory:  [ website section for organizing structure and processes](https://user-images.githubusercontent.com/1076427/145653435-34a1ad82-0512-4c20-84eb-317681bd4197.png) `from` #3
  - [ ]  Process and study exiting style `style guide`,`colors` and `icons` 
    - `@input` 📦 :  [  old styleguide](https://dat-ecosystem-archive.github.io/design/) `from` #3
    - `@input` 📦 :  [  more old icons](https://github.com/dat-ecosystem/dat-icons/tree/master/icons) `from` #3
    - `@input` 📦 :  [  dat colors ](https://github.com/dat-ecosystem/dat-colors) `from` #3
  - [ ]  Process and generate a solution concept for validaton 
     - `@output` ❓ `solution concept`
       - next #15
     - `@output` ❓ `concept Validation`
       - next #15

---

### Summary
In this directory, we try to process the information provided from #3  , filter and put them together for validation. it was noticed that  `User personal` and `history` has been defined, `User story` has been provided through `history`, `style guide` has also been provided. The information provided from #3 would help us create: 
### `solution concept`
- Utilize the information provided to arrange and produce structured contents/material, as well as to connect the pieces for validation.
- This gives more info on how `wireframes/Iterations` is going to look like and how the contents are going to be structured within it.
- concept files are provided via `screenshots and image formats`
### `concept Validation`
- The concept is validated by @serapath .
- We proceed to create `wireframes/Iterations` after validations

**Comment by serapath** [comment]
**feedback `2022.04.27`**

regarding the first point ...
> In this directory, we try to process the information provided form https://github.com/playproject-io/contracting/issues/3 , filter and put them together for validation.

**THIS IS** what i was or am imagining should be the output of the trial phase :-)
So basically, you would create todos and sub todos with sub issues the way you already do it, but now, you slowly go through the list of resources in #3 like you say and take them, one by one and decide under which of the many issues and todos you already made ...and if none of the ones you made, then you can make additional issues or todos ...and then you would link those resource links from #3 as an `@input` :package: [`<name/link of the resource file>`](#) ...until ALL RESOURCES are somwhere being processed in your todo/issue structure :-)



looks good too.
:+1: for the description of what is meant by solution concept
:+1: for the description of what is meant by concept validation

**question1:**
because we work entirely remote and digital, how would the "solution concept" look like?
what is the format? is that a file? multiple files? ...is it a picture? a written text? a slide deck? something else?

as long as thats "nebulous" it is difficult to work towards it, so it would be nice to make that more specific and actually make it 
some sort of `@output` :-)

**question2:**
same as question1, what is that concept validation look like? i guess its about interviewing me and taking notes?
should i record myself and say "yes, i agree with the solution concept" ?? :-) ...what is the tangible output of this?

Is it that you take all the documents from the "solution concept" and make a final iteration to refine it and that is the "validated output" ....either way, it again needs an `@output` :question: `....` i would say.

**Comment by serapath** [comment]
**feedback `2022.04.27`**

so let me share how this could be improved
```
## `@todo`
- [ ] Information Architecture
  -  Draw out inspiration for concept from #3 
     - `@output` :package: [current dat-ecosystem website: https://dat-ecosystem.org]() `from` [#issue 3]()
     - `@output` :factory:  [ Dat ecosystem as a garden]() `from` #3
     - `@output` :factory:  [ dat-ecosystem as a garden Vision/Mission]() `from` #3
     - `@output` :factory:  [ history info 2]() `from` #3
     - `@output` :factory:  [ history info 3]() `from` #3
     - `@output` :factory:  [ sable website section for dat-ecosystem as a garden]() `from` #3
     - `@output` :factory:  [ Joining Rules]() `from` #3
     - `@output` :factory:  [ website section for organizing structure and processes]() `from` #3
  -  Process and generate a solution concept for validaton 
     - `@output` ❓ `solution concept`
       - next #15
     - `@output` ❓ `concept Validation`
       - next #15

```
1. So first the following should probably be todos with checkboxes
> * [ ] Draw out inspiration for concept
> * [ ] Process and generate a solution concept for validaton 
and todos can of course be issues, but they have never a `from` or `next`

2. all the `@output`s for the first todo should probably be `@input`s, because the documents they link to already exit

3. The `@output`s and `@inputs` are always links to documents and never issues and the `from` and/or `next` should just link to `#<issuenumber>` not `issue #<issuenumber>`, so
> - `@output` :package: [current dat-ecosystem website: https://dat-ecosystem.org]() `from` [#issue 3]()

becomes

> - `@output` :package: [current dat-ecosystem website: https://dat-ecosystem.org](https://dat-ecosystem.org) from #3

but you have to fill out the real link from #3 for the website, so

> .... is https://dat-ecosystem.org

which makes it

> - `@output` :package: [current dat-ecosystem website: https://dat-ecosystem.org](https://dat-ecosystem.org) from #3

**Comment by Hornet004** [comment]
- Worklog `28-4-2022`

**Comment by serapath** [comment]
merged into #49
