### ISSUE TITLE
New dat-ecosystem website project plan

### ISSUE THREAD

**Issue by Helenphina** [playproject-io/contracting#17]
## `@todo`

- [ ] Create a New dat- ecosystem website
  - [x] #18 
  - [x] #19 
  - [x] #20 
  - [x] #21 
  - [x] #22 
  - [ ] #31 

## ` @info`
This is a roadmap/plan for building of "dat ecosystem website"
These are the necessary steps/processes to take in order to ensure that this project is successful.

**Comment by serapath** [comment]
**feedback `2022.04.27`**

sweet. looks good, the issue above uses the following formatting
```
### `@todo`

- [ ] Create a New dat- ecosystem website
  >  * `input`❓`Below listed todos`
 - [ ] #18 
- [ ] #19 
- [ ] #20 
- [ ] #21 
- [ ] #22 
  >  * `output`❓`new dat ecosystem website`

## ` @Info`
This is a roadmap/plan for building of "dat ecosystem website"
These are the necessary steps/processes to take in order to ensure that this project is successful.
```

but:
1. todos that are sub steps to be executed to achieve an "higher level summary" task should be indented
2. we dont use `>` in the formatting for marking results (which means inputs or outputs)
3. technically also 2 hashes `##` is enough instead of `###` for the `@todo` marker
4. the `input` and `output` markers have an `@` in front
5. and lastly regarding the content you write "below listed todos", **but** todos can **never** be input or output
  * every todo has to always be a link to a document (e.g. repository, file, picture, figma wireframe, etc...)
    * so you would either need to replace the `@input` with some links from the resource list in #3
    * or you would need to remove it and add those resource input links to the todos in your sub issues
    
so it should be updated like this:
```
## `@todo`
- [ ] Create a New dat- ecosystem website
  - [ ] #18 
  - [ ] #19 
  - [ ] #20 
  - [ ] #21 
  - [ ] #22 
  * `@output`❓`new dat ecosystem website`

## ` @Info`
This is a roadmap/plan for building of "dat ecosystem website"
These are the necessary steps/processes to take in order to ensure that this project is successful.
```

**Comment by serapath** [comment]
merged into #49
