### ISSUE TITLE
Project Brief

### ISSUE THREAD

**Issue by Helenphina** [playproject-io/contracting#18]
## `@todo`

- [ ] Study All the materials/resources (3 days)
  - [ ] Study various websites
  * `@input` 📦 [current dat-ecosystem website: https://dat-ecosystem.org](https://dat-ecosystem.org/)
  * `@input` 📦 [old website - dat.land](https://dat-ecosystem.org/dat.land/)
  * `@input` 📦 [old website - dat-data.com](https://dat-ecosystem-archive.github.io/dat-data.com/)
  * `@input` 📦 [old another website](https://dat-ecosystem-archive.github.io/old-website/)
  * `@input` 📦 [old website - datproject.org](https://datproject.org/)
  * `@input` 📦 [old website - dat.foundation](http://dat.foundation/)
  - [ ] Read materials
  * `@input` 🏭 [dat-ecosystem as a garden Vision/Mission](https://hackmd.io/6T6MwxU8SSefMiQsusFVvg)
  * `@input` 🏭 [Dat ecosystem as a garden](https://hackmd.io/SUqtds4pRcOlRG-Zxqbd7A)
  * `@input` 🏭 [usable website section for dat-ecosystem as a garden](https://user-images.githubusercontent.com/1076427/145653389-814d54e1-148e-4e47-af38-0e34aceba2d9.png)
  * `@input` 🏭 [website section for organizing structure and processes](https://user-images.githubusercontent.com/1076427/145653435-34a1ad82-0512-4c20-84eb-317681bd4197.png)
  * `@input` 🏭 [website section to explain consortium with manifesto and members](https://user-images.githubusercontent.com/1076427/145653435-34a1ad82-0512-4c20-84eb-317681bd4197.png)
  - [ ] Watch resources
   * `@input` 🏭 [old conference videos](https://www.youtube.com/channel/UCbLY5Qg3t3OJbxZZUioqMOQ)
   *  `@input` 📦 [dat-ecosystem project screencast](https://share.vidyard.com/watch/66BS2ddz4XHg8zvShmuJ2e?) 
   * `@input` 📦 [github issue management system](https://share.vidyard.com/watch/ssnP1kGuw5WdWuwJywRrho?) 
   * `@input` 📦 [example project screencast "wizardamigos"](https://share.vidyard.com/watch/V2ThxmUj6tEb3Z8tmBxh9o?) 
   * `@input` 📦 [example project screencast "datdot-ui"](https://share.vidyard.com/watch/paHEaJmW4v63kpcvLyGHyC?) 
   * `@input` 📦 [little checklist and summary](https://share.vidyard.com/watch/Gn99BGZU4JbPHZuYwYxzmV?)
 - [ ] Make a summary project brief slide deck about dat ecosystem (2 days)
   * `@output`❓`Project brief slide deck`
       * Next  #19 

## `@info`
To study all the materials in #3  very well so as to ensure proper understanding of what dat ecosystem is all about and from it create a summary brief slide deck about dat ecosystem.
These websites serves as inspirations to study more about ecosystem [ecosystemmarketplace](https://www.ecosystemmarketplace.com/) , [ecosystem pictures](https://buffalo.finance/buffalo-finance-on-the-binance-smart-chain-ecosystem-map/) and [ecosystem services](http://sweetgum.nybg.org/science/projects/osa/ecosystem-links/)

**Comment by serapath** [comment]
**feedback `2022.04.27`**

looks good, but:
1. formatting should change the same as described in the main issue
2. the **planned** `@input` :question: `Overview` needs to be prdouces first as an `@output` in a different todo
   * so please make or rather refine todos to first create the `@output` :question: `Overview` so it can be used
   * the same is true for the `@output` :question: `Problem Statement`
   * which todos produce is and what kind of document and format will it have? what should I expect? :-)
3. Also the name `Project Brief` sounds more like a result or something that exists already and not like an instruction
   * better would be to add a **verb** like `make Project Brief` if thats what you have in mind
4. Also the `@output` :question: `Solution` sounds vague - so again, is that a file? a figma? a text (and how long)?
   * if it could be based on the project or the list of resources in #3 or just generally more specific, that would help :-)
5. I noticed that the `@output` :question: `Solution` is **nowhere used as an input**, which strongly indicates we dont need it.
   * every output we produce should be an end result (e.g. "the new dat-ecosystem website") ...or used as an input for some other todos ... if its not, we should not produce it :-)
   * `task`: so please use it somewhere as an input or remove it instead :-)

**Comment by serapath** [comment]
**feedback `2022.04.27`**

yes, this is kind of ok, but an **issue** should never be an `@input` or `@output`.
So you basically have to copy over all the inputs in the list of #3 manually and link it as a long list of inputs.

Now what would be much better of course is if you made multiple todos and maybe even issues and link different resource links from #3 under those specific todos where you intend to read and process them to create a more specific output.

Linking them all under the same issue here as one long list would be a simple copy and paste, but it is also a less realistic project plan, because you were realistically wont process all of them at once, but rather group those resources that are related and process them together in a todo to plan some specific part of the project :-)

**Comment by serapath** [comment]
merged into #49
