### ISSUE TITLE
UX Survey

### ISSUE THREAD

**Issue by Helenphina** [playproject-io/contracting#19]
## `@todo`

- [ ] Stakeholders Interview (3 days)
  - [ ] Create stakeholders interview questions
  * `@input`❓`Link to project brief slide deck` from #18 
   * `@output`❓`Link to stakeholders answers`
- [ ] Users Interview (3 days)
  - [ ] Create users Interview questions
  * `@input`❓`Link to stakeholders answers`
   * `@output`❓`Link to users answers`
- [ ] Create user persona (1 day)
   * `@input`❓`Link to users answers`
   * `@output`❓`Link to user persona`
- [ ] create empathy map (1 day)
   * `@input`❓`Link to users answers`
   * `@input`❓`Link to user persona`
   * `@output`❓`Link to empathy map`
- [ ] create user journey map (1 day)
  * `@input`❓`Link to empathy map`
  * `@output`❓`Link to user journey map`
 - [ ] Create User flow Chart (1 day)
   * `@input`❓`Link to user journey map`
   * `@output`❓`Link to user flow chart`
       * Next #20 
   
## `@info`
In this directory, the stakeholders are to be interviewed in order to get their insight about the project (dat ecosystem website). From the stakeholders review, we proceed to interview the end users (targeted audience) of this website so as to know if in anyway they have used a website similar to the one we are working on, the challenges they faced when using it and what they think can be done better/improved on.
From users Interview, we will create user persona and empathy map, so as to clearly identify the pains points and reactions of these users so as to create a better problem solving approach to these challenges. Which will lead us to creating user journey map and user flow chart so as to outline the necessary steps/action a user will take to easily navigate through. The websites below serves as inspirations [Knowing about stakeholders Interview](https://www.epa.gov/international-cooperation/public-participation-guide-stakeholder-interviews) , [Stakeholders Guide](https://adamfard.com/blog/stakeholder-interviews) , [More about users interview](https://learn.marsdd.com/article/interviewing-potential-users/) , [Guide to user persona](https://careerfoundry.com/en/blog/ux-design/how-to-define-a-user-persona/) , [Empathy map](https://www.uxbooth.com/articles/empathy-mapping-a-guide-to-getting-inside-a-users-head/)  , [More to Journey map](https://www.nngroup.com/articles/journey-mapping-101/) , [Drafting a good user flow chart](https://creately.com/blog/diagrams/user-flow-diagram/amp/)

**Comment by serapath** [comment]
**feedback `2022.04.27`**

looks good, **but:**
1. formatting should change the same as described in the main issue
2. all inputs you mention need to be first produces in todos and only then they can be used as input documents
   * could you make the todos here or in other issues to first produce the documents/results that you plan to use as inputs?
3. The name for: `@output` :question: `Link to Interview answers` should be unique
   * so maybe add user answers and stakeholder answers
   * because otherwise it is hard to know which of the documents is meant if they are later used as an input for a todo in a different issue
4. i noticed `User persona`, `User flow chart` and both `Link to interview Answers` are never used as an input for another task
   * `task`: please use them in other todos maybe in other issues as input somewhere to produce the next output
   * ...or otherwise we should just skip it, because it is not an end result and if we dont need them as an input in any specifiable future task to produce the next outputs ...then i dont think we need it :-)
      * we shouldn't produce some outputs just for the sake of producing them :P

**Comment by serapath** [comment]
**feedback `2022.04.27`**


great issue, the way it is structured makes sense to me :+1: 

**but:** :-)

1. I see that you made an output in #18 ...a `Project brief slide deck` and you said you would use it in this issue here in UX Survey, but i don't see it listed as an `@input` to any of the tasks, so i wonder if that slide deck is even needed or if we can skip it.

2. it might make a tiny bit more sense to add the user persona and empthy map outputs directly under their todos instead of under the last todo and if you need the user questions in each of them you would also list that as an input under each of those todos.

3. i wonder where you use the stakeholder questions as an input - do we need them?

4. i just for fun peeked at issue #20 because you marked the
> `@output` :question: `link to user flow chart`
as being used as an input in that issue, but i could not see where it is used

5. in fact, i could not find any future tasks that use the empathy map and persona and flow chart as an input ... so does that mean we can we skip them altogether? :-)

**Comment by serapath** [comment]
merged into #49
