### ISSUE TITLE
application form

### ISSUE THREAD

**Issue by serapath** [playproject-io/contracting#2]
# `@todo` :hammer_and_wrench:
* [x] **tasks here are to be done by our team. applicants please skip and read `@info` section**
    * [x] wait for all applications until the weekend of the deadline `2022.04.22-23:00(UTC0)`
    * [x] watch all application videos received
    * [x] lock the issue comments during the weekend after the deadline passed
    * [x] evaluate submitted screencasts to choose candidate(s)
    * [x] inform and announce selected candidate(s)
        * `@output` :package: [`list of selected candidate(s)`](https://github.com/playproject-io/contracting/issues/2#issuecomment-1107646606)
            - next #3 
---
# `@info` :point_down:

#### [learn more about the gig](https://github.com/playproject-io/contracting/issues/4) :octopus:

---

### :camera_flash: 1. Please, record a 3-5 minute screencast in which you should:
  1. present your portfolio with focus on your outstanding designs and wireframes
  2. show live apps or websites you made or worked on and what you did
  3. present github repos you made or worked on and what you did

**You can use one of these browser extensions to record the screencast:** [screencastify](https://chrome.google.com/webstore/detail/screencastify-screen-vide/mmeijimgabbpbgpdklnllpncmdofkcpn?hl=en), [loom](https://chrome.google.com/webstore/detail/loom-%E2%80%93-free-screen-and-ca/liecbddmkiiihnedobmlmillhodjkdmb), [vidyard](https://chrome.google.com/webstore/detail/vidyard-free-video-and-sc/jiihcciniecimeajcniapbngjjbonjan?hl=en)

### :envelope_with_arrow: 2. To apply, please scroll to the bottom of this issue and make a comment with your application

 **template in markdown syntax**
 ```md
**my application**
- screencast: 
- name: 
- location: 
- business: 
  - 
- profile:
  - twitter: 
  - github: 
- portfolio:
  - 
  - 
```

**here are some examples**
> - screencast: https://www.youtube.com/watch?v=p8bPsE32qBU
> - name: `Ababuo Hamadou`
> - location: :cameroon: `cameroon`
> - business: `freelancer (opencollective.com)`
>   - https://opencollective.com/ababou-hamadou
> - profile:
>   - twitter: https://twitter.com/ababou-hamadou
>   - github: https://github.com/ababou-hamadou
> - portfolio:
>   - https://github.com/ababou-hamadou/figma-wireframe1
>   - https://www.behance.net/ababou-hamadou

---
> - screencast: https://www.youtube.com/watch?v=k6Jn1NhJYGA
> - name: `Aadhya Singh`
> - location: :india: `india`
> - business: `Aadhya Singh Software LLC`
>   - https://www.companyhouse.in/company/india/U63040PN1988PTC049147/a-k-travels-private-limited
> - profile:
>   - twitter: https://twitter.com/aadhya-singh
>   - github: https://github.com/aadhya-singh
> - portfolio:
>   - https://github.com/aadhya-singh/adobe-xd-wireframe1
>   - https://github.com/aadhya-singh/adobe-xd-wireframe2
>   - https://github.com/aadhya-singh/demo-website1
>   - https://www.behance.net/aadhya-singh
  
---
> - screencast: https://www.youtube.com/watch?v=V8evcGT8S7o
> - name: `Alexander Praetorius`
> - location: :gb: `UK`
> - business: `SERASEED LTD`
>   - https://find-and-update.company-information.service.gov.uk/company/09657159
> - profile:
>   - twitter: https://twitter.com/serapath
>   - github: https://github.com/serapath
> - portfolio:
>   - https://github.com/serapath/dom-console
 

### :bar_chart: 3. we will carefully inspect and evaluate all submitted applications
1. we will watch your recorded screencast presentation
2. we will study all links you provide
3. we will discuss with our team and choose most appropriate candidate for our project

**Comment by Hornet004** [comment]
**my application**
>- screencast: https://www.loom.com/share/8cb27284998240f88095ea008d71c364
>
>- name: `Adegoke David`
>- location:  `Nigeria` <sup>NG</sup>
>- business: `Freelancer (upwork.com)`
>   - https://www.upwork.com/freelancers/~017e04fdf4e3e6891d

>- profile:
 >   - twitter: https://twitter.com/dboutcert
 >   - github: https://github.com/Hornet004

>- portfolio:
>    - https://drive.google.com/drive/folders/1FC22unhYTZVdz9IYrU0qWAOMgQ5BR31K?usp=sharing
>    - https://www.figma.com/file/NpeNrbJ0p0KpUmg6AVWiQO/Horbtech-prototype?node-id=202%3A52
>    - https://www.figma.com/file/mxQ6aWFwyUSql3ROHvpcHd/AboutCert?node-id=0%3A1
>    - https://framer.com/share/Stratapp-copy--3BquVTAsPoatxU5SebQd/eXvSJivnARrxM0jVFmZ35R-7%3A950cbsp187vg88

**Comment by isamalf** [comment]
**Name:** Gabe Jones

**Discord:** ism#0581

**Location:** San Francisco, California

**Business:** Freelancer & Internship at Meta

**Profile's:** 
      Twitter: https://twitter.com/isamalfu
      Github: https://github.com/isamalf
      
**Portfolio:**
https://aircoin.cool/index.html
https://kittyninja.io/
https://isamalf.github.io/cheers-website/
https://www.urgaming.io/
https://dribbble.com/shots/18030102-Cannabis-E-Commerce-Store-Landing-Page-Design-Concept
https://dribbble.com/shots/18042704-NFT-Art-Website
https://dribbble.com/shots/18044653-Streaming-Platform-Landing-Page
https://dribbble.com/shots/18044185-Fantech-Future-of-NFT-Website-Landing-Page-Design
https://dribbble.com/shots/18044252-Travelling-in-a-hot-air-ballon

**Comment by ninabreznik** [comment]
> **Name:** Gabe Jones
> 
> **Discord:** ism#0581
> 
> **Location:** San Francisco, California
> 
> **Business:** Freelancer & Internship at Meta
> 
> **Profile's:** Twitter: https://twitter.com/isamalfu Github: https://github.com/isamalf
> 
> **Portfolio:** https://aircoin.cool/index.html https://kittyninja.io/ https://isamalf.github.io/cheers-website/ https://www.urgaming.io/ https://dribbble.com/shots/18030102-Cannabis-E-Commerce-Store-Landing-Page-Design-Concept https://dribbble.com/shots/18042704-NFT-Art-Website https://dribbble.com/shots/18044653-Streaming-Platform-Landing-Page https://dribbble.com/shots/18044185-Fantech-Future-of-NFT-Website-Landing-Page-Design https://dribbble.com/shots/18044252-Travelling-in-a-hot-air-ballon

Gabe, your application is missing a screencast. Please try to add it by the end of the deadline

**Comment by Nathan0-0** [comment]
- ClipChamp : `https://drive.google.com/file/d/1ZoX_2hFH4hVYvL7NyD34-8xXvYzhXIe5/view?usp=sharing`
- name : `Nathan Griesel`
- location : `ZA South Africa`
- business :` Freelancer (MyPersonalSpace)`

profile: 
- github:` https://github.com/Nathan0-0`
- dribble:` https://dribbble.com/0_0Nathan`

portfolio:
- `https://www.figma.com/file/rhVJM1cAG8PQGqMHwJjwjr/RedChips?node-id=0%3A1`

**Comment by Helenphina** [comment]
• Screencast [https://vidmails.com/v/LOf5RXUZfD](https://vidmails.com/v/LOf5RXUZfD) 

• Name: `Helen Nnamani`

• Location: `Nigeria` `NG`

• Business: `Freelancer (Upwork.com)`
[https://www.upwork.com/freelancers/~01b934f87e88ab62df](https://www.upwork.com/freelancers/~01b934f87e88ab62df) 

• Profile:
     Twitter: [https://twitter.com/Helenphina1?s=09](https://twitter.com/Helenphina1?s=09) 
     GitHub: [https://github.com/Helenphina](https://github.com/Helenphina) 

• Portfolio:
[https://heylink.me/helenphina](https://heylink.me/helenphina) 
[https://www.behance.net/helenphina](https://www.behance.net/helenphina) 
[https://dribbble.com/HelenPhina](https://dribbble.com/HelenPhina)

**Comment by CodeLawd** [comment]
- Screencast [https://watch.screencastify.com/v/bgiVD5B9FI4B3Y2pPpLG](https://watch.screencastify.com/v/bgiVD5B9FI4B3Y2pPpLG)
- Name: `Alexander Joshua`
- Location: `Nigeria`
- Business: `Software Developer/ UI/UX Designer`
[https://codelawd.vercel.app/](https://codelawd.vercel.app/)

- Profile
Twitter: [https://twitter.com/CodeLawd](https://twitter.com/CodeLawd)
Github: [https://github.com/CodeLawd](https://github.com/CodeLawd)

- Portfolio
[https://www.figma.com/file/wf7ImVGoKQLFcbQZz8bjPe/TalkamNaija-New-Interface?node-id=0%3A1](https://www.figma.com/file/wf7ImVGoKQLFcbQZz8bjPe/TalkamNaija-New-Interface?node-id=0%3A1)
[https://www.figma.com/file/NjYFdTT7tUhJxXEGla2COn/eat-binchi?node-id=801%3A2353](https://www.figma.com/file/NjYFdTT7tUhJxXEGla2COn/eat-binchi?node-id=801%3A2353)
[https://www.figma.com/file/xYxu6Sj7RpCI2gmBgwRvDf/Ear1a?node-id=0%3A1](https://www.figma.com/file/xYxu6Sj7RpCI2gmBgwRvDf/Ear1a?node-id=0%3A1)
[https://www.figma.com/file/21qaCTzroVLhz8Stq7KaK9/SPACESHIP?node-id=0%3A1](https://www.figma.com/file/21qaCTzroVLhz8Stq7KaK9/SPACESHIP?node-id=0%3A1)

**Comment by serapath** [comment]
@isamalf
Hello Gabe Jones,
we checked your portfolio. it seems you dont use twitter and on github you did some phyton and css. Thats an interesting combination. Your portfolio has some very nice examples and some ok ones. The css examples on github and some in the portfolio seem to come from templates, maybe wordpress. you also did not record the 3-5 minutes screen cast to explain your work and share your skills. Some portfolio pages stood out because they are very beautiful. The CSS example pages on github look ok, but nothing stood out and it feels like they were generated with a tool when looking at the raw css. Our assumption is that you might be able to adapt templates to quickly make some landing pages, but you might not have much experience customizing pages or even complex apps from scratch. We also didn't see any wireframes and we are looking for wireframing.

I think we might not be a match but we will continue to look for people from time to time, so maybe next time it might work out if you include some wireframing and a video where you explain your portfolio and show that you do know design and css when it comes to custom UI/UX requirements instead of adapting templates.

---

@CodeLawd 
Hello Alexander Joshua
You have an interesting name. I am Alexander and we have also a Joshua on our team already, thats a funny coincidence, but anyway. Your website lookg great and your twitter profile is active and suggests you are into vanilla Javascript too.
You seem to be self taught, which is great and you do full stack (backend/frontend/mobile).
Thats much more than we need, we never use frameworks and work with raw web apis and vanillaJS. You even write articles and brand yourself actively on social media.
Your github repos show you do coding too. A lot is related to react, which is what we dont do.
Your Page suggests you do Adobe Xd but we could even see 4 quite impressive figma wireframes. They look beautiful and some of them also include more complex apps.
The TalkamNaija Page is quite impressive. Wish they had an app like this in my country,
so citizens could report issues and the government would resolve them :-)
Really cool portfolio. One question for me is if you did all of them yourself or if you have a team and run some sort of agency - that wasn't really clear. For a solo person your portfolio is absolutely stunning, but if you have a team the work still looks pretty solid.

**If you are available, let us know, we would totally love to invite you for the 48hours trial phase during monday/tuesday to see if we can work together :small_airplane:**


-------------------------------------
@Nathan0-0 
Hello Nathan,
you dont seem to have a twitter account and your github account is blank.
The dribble account only shows very few and basic designs.
The figma link looks beautiful, but as a page its also a simple one in terms of functionality and complexity. It looks more like a flyer, but definitely aesthetically pleasing.
Also your second safari or zoo tickets page looks nice and a bit more complex. Sadly your video does not have audio and no links are provided, so I don't know if you were explaining anything.
I wonder if you did those pages from scratch all on your own or somebody else did them?
Did you come up with the entire page concept and designed and implemended it? What was provided by the client? Do you use a program to design those pages? Which one do you use?
Do you write the CSS yourself? These things are not clear, but the two figma wireframes (the second is sadly not linked) They both look nice. Oh - I think maybe its google drive, but the video resolution is quite bad. Maybe another screencast recording tool would have been better.

All in all you don't have app wireframes and without the audio we think there might be communication problems between us and you might also not have any experience for the kind of work we are looking for, but if your portfolio more items and also wireframes that show you do complex app concepts and you could communicate those with audio in a high resolution screen cast it might totally work out next time. We will continue to look for people from time to time. 
So I am sad to say maybe this time doesnt work yet, but you also applied last time and I can see some serious improvements, so please apply again next time, because I see lots of potential.
You might already be a great candidate and we just have trouble seeing for lack of audio and for lack of github/twitter activity to tell and for lack of portfolio links. Please don't hide or rather work on providing a bit more on that front for next time.

-------------------------------------
@Hornet004

Hello Adegoke,

your twitter account seems to be more of an account for private stuff, thats fine :-)
It looks like you already came in touch with some crypto projects in the past.
Your github profile looks cool, but beside an html repo it has C and Shell stuff,
which are not relevant to what we are looking. But good to know you used github and know it already. The portfolio link includes a CV, which is nice, but we usually dont really mind what people did in the past or what official qualifications they have but only look at their work and portfolio. The framer UI is interesting, even though i don't completely understand it. I think its a quiz app?  Now the figma wireframes look pretty cool and are mostly about complex apps, which is kinda what we need. One is even some sort of elearning app and this is also what we are working on amongst other things. Its a good portfolio. Thanks for sharing. Watching your video to walk through the wireframes was ok. Thanks for communicating the concepts behind each.
You said "we" a lot so it made me wonder who are the others and which parts did you do and what did others do. Anyway, your portfolio looks good to me :-)

Now if you want you can try and participate in the 48h trial phase on monday for which we will release details soon. We can't promise anything other than that we will pay for it as described in the application process. A lot of things are important, a UX that makes sense, a high fidelity design that matches the character of the apps we make well. Communication with little misunderstandings and being able to work with the remote async organization system we use to work. We can't promise anything, but also we will be checking for people from time to time so if not now it might work in the future.

**Anyway, you are invited to participate in the trial phase on monday if you want. Please let us know :small_airplane:**

-------------------------------------
@Helenphina
Hello Helen,

First opened your upwork profile and it gives a good first impression.
Its cool to see your twitter timeline. Quite inspirational.
I learned about "Challau", a Metaverse Campus - haha, pretty cool.
I also saw a CSS functions cheatsheet. Thats wonderful too. I don't know the majority of those functions, but i guess mastering them can help with coding some really impressive designs.
You really seem to live design and UI/UX. Your github profile is entirely empty, but you mentioned that before. I really love your dribble. All the designs look stunning. For us more relevant is of course stuff that looks like apps. There is even one that includes an app for a watch and it looks quite cute. The merridian Dashboard also looks interesting and the Home Services Page too.
Sadly its unclear if that is or was a real project. Behance shows the same items, but a few more.
The NomaHotel looks nice. The Vova Transfer app has a high resoltuoin but looks a bit unfinished. The Movie looks good and the most amazing is the Teleportation App.
The Teleoprtation App has complex UI/UX and looks very clean. It's an amazing portfolio piece.

The recorded screencast sadly has no audio, so i don't really know what you explain.
The wireframes look good, but it is hard to understand the details and concepts
without the audio, but it still looks good from what i can understand.

**Now if you want to try to participate in the trial phase on monday for 48hours which is paid as described in the application process, you are invited to join. :small_airplane:**

**Comment by serapath** [comment]
### application phase result
@Hornet004 @CodeLawd @Helenphina @isamalf  @Nathan0-0 

Thank you all very much for participating. You are all awesome.
Of course - the best match always depends on whether a specific profile and skill set matches with a specific project and whether we are able to assess things correctly - there is only so much we can do in a short time when reading and looking over a specific application.

We are happy if all of you feel like applying also in the future when we look again for more candidates :slightly_smiling_face: 

---

### About the trial phase

With the limited time and information we have our team chose to offer participating in the trial phase to @Hornet004 @CodeLawd @Helenphina :slightly_smiling_face: 

**Here a few words about the trial phase on monday:**

1. The trial project is about a website app with a long (8 years history) which we and a few others are the "end users" of, so we know everything about it and can answer on behalf of all other end users if there are any questions.

2. We want to see if candidates can work with our project and task management system and style of organizing tasks using our tools here on github, so i will record a little screencast before monday and explain it, but you can already see it in action here on github during the application process. **One important part to notice and practice is that we break our project not into "phases" but into "components/parts", where each component/part might have phases**
So instead of making a plan with phases and then work on all components in each project phase to do what is relevant in that phase, we instead make tasks for each part or component of the project and in the details of that tasks it might have its own phases - so it's the other way around than what people do usually.

3. We also want to see if candidates can process a quite large amount of input for this project which has 8 years of history already. Feel free to ask any and as many questions as you want and take notes or add screenshots or links to specific parts of the provided materials or anything you need to remember or include in the detailed project plan for later use when working on the project to make sure everything is covered.

4. any sketches, plans, inspirational links, research links and thoughts and ideas you lookup online or have in your mind while processing the materials should be added and/or linked next to the project plan structure next to each task for the project that you are supposed to make in those 48 hours to make.

5. Additionally, because we work remote and async with people who record 3-5 minutes screencasts, sometimes multiple ones per day to communicate - please record a screen cast with audio and walk us through the project plan and all the ideas and thoughts you have.

I will be available on discord/twitter/github to answer questions and help with what i can :-)

---

@Hornet004 @CodeLawd @Helenphina 

Please comment below if you are interested in participating in the 48 hour trial phase on monday.
I will update al missing details until monday. If you have any questions, please let me know.

**Comment by Helenphina** [comment]
Thank you very much for this opportunity
I'm interested in the Trial Phase

**Comment by Hornet004** [comment]
Superb!!! - I'm really looking forward to the Trial Phase:) - In terms of the emphasis on "we", the projects mentioned involve Founders, developers, and of course, me as a UX designer; we rub brains, share ideas, and collaborate. It's a more collaborative team feeling when I use the word "we" Instead of "I".

**Comment by CodeLawd** [comment]
Thank you Alexander for your honest feedback. I am flattered by your words 😄, It's good to know we bear the same name.

Yes, I have a partner with me whom I work with occasionally. He basically manages the UI/UX deliverables (Wireframes, colour palette, graphics elements, fonts, etc) while I manage the implementations(writing pure CSS and vanilla javascript). We believe that individual task specification makes the work easier and faster. 

We both worked on each portfolio together as I get to make comments, reviews and Technical feasibility analysis on the designs. I also get to work on some UI/UX parts based on the project.

Sure, We are very pumped to participate in the 48 hours trial phase.

**Comment by serapath** [comment]
Lovely :-)

alright.
everyting is ready for you to start the trial phase project.
Its a lot of instructions, so please read everything carefully :-)

I will be busy with my work during the entire day, but in the late afternoon, i will check and respond to questions and give feedback.

The 48hours of the trial phase start in the afternoon.
So the trial phase ends the day after tomorrow in the afternoon/evening.


Here is the link to the trial phase issue
We continue in the trial phase issue now
* #3
