### ISSUE TITLE
UI Design

### ISSUE THREAD

**Issue by Helenphina** [playproject-io/contracting#21]
## `@todo`

- [ ] Create Site Map (1 day)
   * `@input` 📦 [current dat-ecosystem website: https://dat-ecosystem.org](https://dat-ecosystem.org/)
   * `@input`❓`icons` from #20 
   * `@input`❓`buttons` from #20 
   * `@input`❓`textholder` from #20 
    * `@output`❓`Link to website site map`

- [ ] Make Sketches (1 day)
    * `@input`❓`link to website site map`
     * `@output`❓`Link to sketches`

- [ ] Create Wireframes (3 days)
    * `@input`❓`Link to sketches`
    * `@output`❓`link to wireframes`

- [ ] Create High fidelity Design (5 days)
     * `@input`❓`link to wireframes`
     * `@output`❓`link to high fidelity design`
       * Next #22 

## `@info`
In this directory, the necessary features for the creation of dat ecosystem website is being worked on. Firstly, we will create a Site map for the website from the current website they have, from the site map we will make sketches of what the new dat ecosystem website should be. From the sketches we will create a low fidelity Design which is also known as wireframes, from the wireframes we will proceed to create the high fidelity Design for the website. The following links serve as inspirations [Learn about site map](https://developers.google.com/search/docs/advanced/sitemaps/overview) , [UI Sketching](https://uxmisfit.com/2017/11/12/ui-sketching-how-to-make-it-right-and-why-you-should-do-this-in-all-projects/amp/) , [More about wireframing](https://medium.com/detaux/what-is-ui-ux-wireframe-designerrs-46dac9c8a153) , [Prototyping](https://blog.prototypr.io/high-fidelity-prototyping-what-when-why-and-how-f5bbde6a7fd4)

**Comment by serapath** [comment]
**feedback `2022.04.27`**

this one looks brillian and makes sense, **but**
1. the formatting
2. which inputs are needed and used to solve the tasks
3. where are the outputs used to move towards our final goal which is the website? :-)

**Comment by serapath** [comment]
**feedback `2022.04.27`**

brilliant, i really like the issue. makes sense to me, also intermediary inputs are re-used. I am wondering about the `images` though, they seem to be not re-used anywhere ... did you forget or can we skip producing images?

3. lastly - do you consider
* `@output` :question: `link to high fidelity design`
* `@output` :question: `link to high fidelity design prototype`
to be final outputs? ...because again i can't see them being used anywhere.
So if you consider them final outputs of the project, then you can add the additional icon after the :question: :checkered_flag: :-)
...so i wont be looking for other todos where those are the inputs.

4. **but** on the other hand you mentioned that this would be used as input in Web UI Development :-) I can only see the `High Fidelity Design` being an input, but it also lacks the from property to indicate that, so let me give an example below how those should actually look like just to make sure what you mean.


**this issue**
```
...

- [ ] Create High fidelity Design
     * `@input`❓`link to wireframes`
     * `@output`❓`link to high fidelity design`
         * next #22 
     * `@output`❓`link to high fidelity design prototype`

...
```

and **the next issue**
```
...

- [ ] Implementation of the UI design
  * `@input`❓`link to high fidelity design` from #21
  * `@output`❓:checkered_flag: `a working high fidelity Design (New dat ecosystem website)`
     * next #31 

...
```

**Comment by serapath** [comment]
merged into #49
