### ISSUE TITLE
interactive value network visualization component

### ISSUE THREAD

**Issue by serapath** [playproject-io/contracting#33]
## `@todo`
- [ ] design interactive info visualization concept for dat-ecosystem "supply network" of projects & modules
  - [ ] #35
  - [ ] Using previously collected projects and people information, categorize and organize the information as an infographic of the whole dat ecosystem.
    - [ ] #34
    - [ ] decide how filtering and zooming in and checking details works
       - [ ] decide how a user can filter to only show modules which depend on a given list of modules or have a specific given list of other modules as dependents
       - [ ] #36
    - [ ] decide for interactive visualization and start iterating the UI and UX in wireframes
      - `@input` :question: `interaction model` from #36
      - `@input` :question: `complete list of inspiration & ideas` from #34
      - `@output` :question: `infovis wireframes`
    - [ ] break down visualization into seperate composable web components
      - `@input` :question: `interaction model`
      - `@input` :question: `complete list of inspiration & ideas` from #34
      - `@input` :question: `infovis wireframes`
      - `@output` :question: `list of web components`
    - [ ] refine or annotate value network json or text files to include all data required by the infovis
      - `@input` :question: `value network json or text files` from #35
      - `@input` :question: `files and folders with the example assets` from #35
      - `@output` :question: :checkered_flag: `value network json files with links to assets`
  - [ ] implement and style static page info-viz page with dummy data
    - `@input` :question: `complete list of inspiration & ideas` from #34
    - `@input` :question: `infovis wireframes`
    - `@input` :question: `list of web components`
    - `@input` :question: `value network json files with links to assets`
    - `@output` :question: :checkered_flag: `static info-viz page`

---

## `@info`
...
