### ISSUE TITLE
search/gather list of inspiration and ideas for visualisations and add to the list below to evaluate

### ISSUE THREAD

**Issue by serapath** [playproject-io/contracting#34]
## `@todo`
- [ ] search/gather list of inspiration and ideas for visualisations and add to the list below to evaluate
  - [ ] search online for additional inspiration
    - `@output` :question: `additional list of inspiration and idea links`
  - [ ] analyze all input links below and collect **the best examples of each type** to show **all their features** in a condensed inspirational summary list
    - `@input` :package: [`interactive graphics to visualize JS ecosystem`](https://2020.stateofjs.com/en-US/features/)
    - `@input` :package: [`some ways of doing eocysstem maps with pros/cons`](https://startupstatus.co/category/map/)
    - `@input` :package: [`ecosystem circles`](https://cdn.substack.com/image/fetch/f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fbucketeer-e05bbc84-baa3-437e-9518-adb32be77984.s3.amazonaws.com%2Fpublic%2Fimages%2Fe945a6d6-d7e8-4e34-907e-e272fe37f0e5_1600x900.jpeg)
    - `@input` :package: [`stack segments based ecosystem map`](https://www.reddit.com/r/EthGamers/comments/p2yyi2/the_nft_gaming_metaverse_ecosystem_map/)
    - `@input` :package: [`table listing`](https://cdn.substack.com/image/fetch/f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fbucketeer-e05bbc84-baa3-437e-9518-adb32be77984.s3.amazonaws.com%2Fpublic%2Fimages%2F93430033-8873-49c4-8a5a-ca27c6009ed6_1600x900.jpeg)
    - `@input` :package: [`pinterest ecosystem map inspiration`](https://www.pinterest.at/search/pins/?q=ecosystem%20map&rs=typed&term_meta[]=ecosystem%7Ctyped&term_meta[]=map%7Ctyped)
    - `@input` :package: [`global startup blockchain map`](https://www.pinterest.cl/pin/813814595139343933/)
    - `@input` :package: [`funky hexagon map`](https://twitter.com/0xPolygon/status/1395047808860708870?s=20)
    - `@input` :package: [`ecosystem mindmap`](https://ccecosystems.news/en/the-business-side-of-the-blockchain-map/)
    - `@input` :package: [`little pinterest board of listing maps`](https://www.pinterest.de/vladymyr/blockchain/)
    - `@input` :package: [`small and big structured ecosystem boxes`](https://www.europeworldnews.com/at-what-price-can-ethereum-be-delivered-with-update-2-0/)
    - `@input` :package: [`colored box mid circle ecosystem map`](https://fintechnews.hk/8603/blockchain/blockchain-hong-kong-ecosystem-map-2019/)
    - `@input` :package: [`complex connected ecosystem infovis`](https://www.slideshare.net/RichardWarren3/firstpartner-2016-blockchain-ecosystem-market-map)
    - `@input` :package: [`crypto ecosystem v2`](https://medium.com/@SVasin/the-crypto-ecosystem-v2-aea76bde5457)
    - `@input` :package: [`partial ecosystem map`](https://www.reddit.com/r/ethtrader/comments/htug3p/a_partial_look_at_the_ethereum_ecosystem/)
    - `@input` :package: [`titled ecosystem map boxes`](https://u.today/charles-hoskinson-debunks-ghost-chain-fud-with-cardano-ecosystem-map)
    - `@input` :package: [`nice designed ecosystem boxes`](https://www.fatcatfun.com/p/nftmap?s=r)
    - `@input` :package: [`numbered ecosystem cards dashboard`](https://outlierventures.io/research/token-interoperability-in-community-token-economies/)
    -  `@input` :package: https://blockchain.news/analysis/Hong-Kong-Blockchain-Ecosystem-Feb-2020-New-Members
    - `@input` :package: [`logo bubble`](https://cryptoseq.medium.com/the-avalanche-ecosystem-is-rapidly-expanding-private-securities-ilos-dexs-synthetics-663f07ee4a34)
    - `@input` :package: [`ecosystem list pictures`](https://buffalo.finance/buffalo-finance-on-the-binance-smart-chain-ecosystem-map/)
    - `@input` :package: https://blockchainhub.net/blog/blog/mapping-the-german-blockchain-ecosystem/
    - `@input` :package: https://twitter.com/defiprime/status/1153350180437016578
    - `@input` :package: [`blockchain project ecosystem 2017`](https://imgur.com/a/xvTjM)
    - `@input` :package: https://coinvigilance.com/mapping-out-the-non-fungible-token-ecosystem/
    - `@input` :package: https://twitter.com/chainstackhq/status/1386636509416083462
    - 
    - `@input` :package: [`colored ecosystem map sections`](https://blockchain.news/analysis/hong-kong-blockchain-ecosystem)
    - `@input` :package: [`techchrunch ecosystem`](https://techcrunch.com/2017/10/16/mapping-the-blockchain-project-ecosystem/?guccounter=1&guce_referrer=aHR0cHM6Ly93d3cuZ29vZ2xlLmNvbS8&guce_referrer_sig=AQAAAFaMH26glO_4HfwS0iWzt_fNI3sT9cxmZxer9yuaQY1eLyMW3bQRmtEqzRnvitgrtNIdenk5OrQVc6zMnCD1vsG03UW3xLgKNsi-YDbzt5m8q3l9C42DGgpakVRQ4hH9I10P7JoZ_qDECFJl3tOQcNqGUuIcHHDVc5S8weRZjZiZ)
    - `@input` :package: [`blockchain ecosystem techchrunch 2017`](https://techcrunch.com/2017/10/16/mapping-the-blockchain-project-ecosystem/)
    - `@input` :package: [`mini blockchain ecosyste map`](https://dashboard.incryptohub.com/blockchain/ethereum/)
    - `@input` :package: https://twitter.com/n2ckchong/status/1373533273398243328
    - `@input` :package: https://www.panewslab.com/en/articledetails/N3913228.html
    - `@input` :package: https://twitter.com/meter_io/status/1241811403763265536
    - `@input` :package: [`pinterest ecosystem visualizations`](https://www.pinterest.de/pin/444519425726321967/)
    - `@input` :package: [`defi ecosystem`](https://tokeny.com/defi-ecosystem/)
    - `@input` :package: [`etheruem L2 map`](https://twitter.com/loopringorg/status/1376705979656634373?lang=eu)
    - `@input` :package: [`eth defi ecosytem 2021`](https://www.reddit.com/r/ethereum/comments/n482pi/the_eth_defi_ecosystem/)
    - `@input` :package: [`educational defi map`](https://www.reddit.com/r/ethtrader/comments/hhxg1q/defi_map/) 
    - `@input` :package: [`defi ecosystem`](https://www.panewslab.com/en/articledetails/N3913228.html)
    - `@input` :package: [`ethereum defi ecosystem`](https://cryptodiffer.com/analytics/ethereum-defi-ecosystem)
    - `@input` :package: [`forrester research - tech ecosystem`](https://www.forrester.com/apac/tech-ecosystem/)
    - `@input` :package: [`ethereum defi-project-map`](https://thedefiant.io/defi-projects-map/)
    - `@input` :package: [`etherem market map june 2017`](https://medium.com/hackernoon/ethereum-market-map-june-2017-d13928e4319e)
    - `@input` :package: [`project listing by type`](https://defiprime.com/ethereum)
    - `@input` :package: [`reef ecosystem map`](https://medium.com/reef-finance/introducing-the-reef-ecosystem-map-july-2021-cea381c58fe4)
    - `@input` :package: [`dat-ecosystem as garden of projects`](https://www.google.com/search?q=forrester+gardener+ecosystem+project&tbm=isch&ved=2ahUKEwij8sHH5K7yAhVL86QKHVLsCpgQ2-cCegQIABAA&oq=forrester+gardener+ecosystem+project&gs_lcp=CgNpbWcQAzoECAAQQzoFCAAQgAQ6BggAEAgQHjoECAAQGDoGCAAQChAYUIsWWPhUYMhVaARwAHgAgAFziAGqHZIBBDM0LjaYAQCgAQGqAQtnd3Mtd2l6LWltZ8ABAQ&sclient=img&ei=Ds8WYaOzJMvmkwXS2KvACQ&bih=1015&biw=2048)
    - `@input` :package: [`anvakas npm galaxy`](http://npm.anvaka.com/#/view/2d/browserify)
    - `@input` :package: https://twitter.com/OpenVisConf/status/863138059935780864
    - `@input` :package: https://twitter.com/johnmaeda/status/1067607814867206145
    - `@input` :package: https://twitter.com/n2ckchong/status/1373533273398243328
    - `@input` :package: [`a map info visualization`](https://anvaka.github.io/greview/cracking-code-interview/1/)
    - `@input` :package: [`more background of the map visualization`](https://anvaka.github.io/greview/)
    - `@input` :package: [`twitter example 0 by anvaka`](https://twitter.com/anvaka/status/1033006592315121664)
    - `@input` :package: [`twitter example 1 by anvaka`](https://twitter.com/anvaka/status/1031782716864311296)
    - `@input` :package: [`twitter example 2 by anvaka`](https://twitter.com/anvaka/status/1262052384294895616)
    - `@input` :package: [`twitter example 3 by anvaka`](https://twitter.com/anvaka/status/1030499971663974405)
    - `@input` :package: [`twitter example 3 by anvaka`](https://twitter.com/anvaka/status/904442641802190848)
    - `@input` :package: [`twitter example 3 by anvaka`](https://twitter.com/anvaka/status/870686593111121921)
    - `@input` :package: [`defi ethereum ecosystem`](https://medium.com/@taker.exchange/taker-exchange-taker-tokenomics-matters-d4166d5f4e90)
    - `@input` :package: [
    - `@input` :package: https://ecosystem.ipfs.io/
    - `@input` :package: https://ipfs-ecosystem-develop.on.fleek.co/
    - `@input` :package: https://ecosystem.ipfs.io/showcase/
    - `@input` :package: https://ecosystem.ipfs.io/showcase/?category=industry
    - `@input` :package: https://ecosystem.ipfs.io/showcase/?category=focus
    - `@input` :package: https://ecosystem.ipfs.io/showcase/?category=benefits
    - `@input` :package: https://github.com/ipfs-shipyard/ecosystem-directory
    - `@input` :package: https://github.com/ipfs/awesome-ipfs/issues/304
    - `@input` :package: [`ipfs ecosystem google images`](https://www.google.com/search?q=ipfs+ecosystem&newwindow=1&source=lnms&tbm=isch&sa=X&ved=2ahUKEwjN0rPm6a7yAhUhg_0HHYo7C1cQ_AUoAXoECAEQAw&biw=2048&bih=1015)
    - `@input` :package: [`ecosystem map google images`](https://www.google.com/search?q=ecosystem+map&tbm=isch&ved=2ahUKEwj83pSZ67T3AhUL_BoKHeUgBRcQ2-cCegQIABAA&oq=ecosystem+map&gs_lcp=CgNpbWcQAzIFCAAQgAQyBQgAEIAEMgUIABCABDIFCAAQgAQyBQgAEIAEMgUIABCABDIFCAAQgAQyBQgAEIAEMgUIABCABDIFCAAQgAQ6BAgAEEM6CwgAEIAEELEDEIMBOggIABCABBCxAzoHCAAQsQMQQzoKCAAQsQMQgwEQQ1DyBFiPDmDuD2gAcAB4AIABsgGIAdUHkgEEMTIuMpgBAKABAaoBC2d3cy13aXotaW1nwAEB&sclient=img&ei=q4ZpYrzdGYv4a-XBlLgB&bih=1015&biw=2048#imgrc=I56nnRCqc8LmaM)
    - `@input` :package: https://fediverse.party/
    - `@input` :package: https://npmgraph.js.org/?q=hypercore
    - `@input` :package: https://github.com/npmgraph/npmgraph
    - `@input` :package: [`hypergraphs google images`](https://www.google.com/search?q=hypergraph&newwindow=1&bih=1152&biw=1097&hl=en&source=lnms&tbm=isch&sa=X&ved=2ahUKEwjLl8m08LT3AhVOQkEAHVC6B9YQ_AUoAXoECAEQAw)
    - `@input` :package: [`hypergraph wikipedia`](https://en.wikipedia.org/wiki/Hypergraph)
    - `@input` :package: [`graph vs hypergraph`](https://www.angioi.com/visualizing-hypergraphs-networkx/)
    -  `@input` :package: [`titled labeled map sections`](https://fintechnews.sg/34478/blockchain/blockchain-singapore-map/)
    -  `@input` :package: [`grouped listing`](https://www.orbs.com/orbs-ecosystem-expansion-whats-next/)
    - [ ] refine and annotate final list of inspirational visualizations
      - `@output` :question: summary list of links with the best inspiration` 
  - [ ] summarize in a list which parts of which inspirational links go into the final list
    - `@input` :question: summary list of links with the best inspiration`
    - `@input` :question: `additional list of inspiration and idea links`
    - `@output` :question: `complete list of inspiration & ideas`
    - next #33

---

## `@info`

The internet should be searched for additional inspiration and some discussion to come up with ideas which to choose and how to combine which parts should happen too to figure out how to make everything explorable, discoverable, browsable, searchable, filterable, etc... by a user who wants to learn about it
