### ISSUE TITLE
design a first iteration of some example/demo data which the visualization is based on

### ISSUE THREAD

**Issue by serapath** [playproject-io/contracting#35]
## `@todo`
- [ ] design a first iteration of some example/demo data which the visualization is based on
  - `@input` :package: [`example: see "dependencies" and "dependents" tab`](https://www.npmjs.com/package/hypercore)
  - `@input` :package: [`example: person maintaining modules`](https://www.npmjs.com/~mafintosh)
  - `@input` :package: [`example: github dependencies`](https://github.com/hypercore-protocol/hypercore/network/dependencies)
  - `@input` :package: [`example: github dependents`](https://github.com/hypercore-protocol/hypercore/network/dependents)
  - `@input` :package: [`example: dependencies and other data in package.json`](https://github.com/hypercore-protocol/hypercore/blob/master/package.json)
  - `@input` :package: [`example: github org infos`](https://github.com/hypercore-protocol)
  - `@input` :package: [`example: contributors to module`](https://github.com/hypercore-protocol/hypercore/graphs/contributors)
  - `@input` :package: [`example: socket.dev page for hypercore`](https://socket.dev/npm/package/hypercore)
  - [ ] write down some sort of test data of modules and their dependents and dependencies and the maintainers (people or organisations) ideally in json format to include data from inputs
  - `@output` :question: `value network json or text files`
    - next #33
  - [ ] choose some avatars, organisation or project logos, project links and other information available through input links (e.g. projects links, websites, etc)
  - `@output` :question: `files and folders with the example assets`
    - next #33

---

## `@info`

just pick some modules and search the links above for data that is available about them to write down a small example data set that can be used to visualize and browse/explore interactively
