### ISSUE TITLE
decide how to filter modules to only show modules maintained by specific organisations or people

### ISSUE THREAD

**Issue by serapath** [playproject-io/contracting#36]
## `@todo`
- [ ] decide how to filter modules to only show modules maintained by specific organisations or people
  - [ ] e.g. show modules that most frequently get updated 
  - [ ] e.g. show modules which have a lot of open issues
  - [ ] e.g. show modules that are often downloaded
  - [ ] e.g. brainstorm about what other kinds of information the interactive infovis should have to make the data explorable
  - [ ] e.g. make table with filtering and summary (use data table framework)
  - `@output` :question: `interaction model`
    - next #33

---

## `@info`
The options available to a user to explore the data through the interactive info visualization should help them to answer all the important questions and get a better understanding and overview over the dat-ecosystem
