### ISSUE TITLE
Design Brief 

### ISSUE THREAD

**Issue by CodeLawd** [playproject-io/contracting#38]
## `@todo`
**Getting to know more about dat-ecosystem (WK1)**
- [ ] **Videos to watch (3 hours)**
- Watch All in a day and relate questions to Sarapath and his team in video format if neccesary
    `@input` :factory: [old conference videos](https://www.youtube.com/channel/UCbLY5Qg3t3OJbxZZUioqMOQ) from [#issue 3](https://github.com/playproject-io/contracting/issues/3)
`@input` :package: [dat-ecosystem project screencast](https://share.vidyard.com/watch/66BS2ddz4XHg8zvShmuJ2e?)
`@input` :package: [example project screencast "datdot-ui"](https://share.vidyard.com/watch/paHEaJmW4v63kpcvLyGHyC?)
`@input` :package: [example project screencast "wizardamigos"](https://share.vidyard.com/watch/V2ThxmUj6tEb3Z8tmBxh9o?)
`@input` :package: [github issue management system](https://share.vidyard.com/watch/ssnP1kGuw5WdWuwJywRrho?)
- [ ]  **Materials to read (1 hour)**
    `@input` :factory: [current dat-ecosystem website: https://dat-ecosystem.org](https://dat-ecosystem.org/)
    `@input` :factory: [dat-ecosystem as a garden Vision/Mission](https://hackmd.io/6T6MwxU8SSefMiQsusFVvg) 
    `@input` :factory: [Inspiration1](https://pastebin.com/SR2bpZCL) 
    `@input` :factory: [dat-ecosystem twitter account](https://twitter.com/dat_protocol) 
    `@input` :factory: [list of historic dat ecosystem projects](https://github.com/dat-ecosystem-archive/projects) 
    `@input` :factory: [more dat ecosystem projects](https://github.com/dat-ecosystem-archive/project-updates) 
    `@input` :factory: [website section for organizing structure and processes](https://user-images.githubusercontent.com/1076427/145653435-34a1ad82-0512-4c20-84eb-317681bd4197.png) 
    `@input` :package: [initial dat whitepaper](https://github.com/dat-ecosystem-archive/whitepaper) 
    `@input` :package: [dat design](https://dat-ecosystem-archive.github.io/design/) 
    `@input` :package: [dat colors](https://github.com/dat-ecosystem/dat-colors) 
- [ ]  Make a design brief document about the dat ecosystem (3 days)
- `@output` :question: `Design brief document`
     - Next #39 

----
## `@info`
Note: Information gathered above will help us create a design brief document which is very important for us not to get clouded.

**Comment by serapath** [comment]
**feedback `2022.04.28`**

looks good to me

1. but you have a todo `Videos to watch (3 hours)` whith an input that has a check box, but the input should have no check box and if you want it, then make multiple todos each with an input and mark the todos as done

2. same for the next list of inputs which should not have checkboxes and if you want that then make an additional todo for each input and mark that instead of the todo.

3. there is a `next` label that is **not** a sub bullet point of an `@output` and in general this issue does not create any outputs, which means it should not have next and if an issue or todos create no outputs at all we have no reasons to do any of the todos in the first place, so you need to add at least one output :-)


```

**Comment by serapath** [comment]
merged into #49
