### ISSUE TITLE
dat-ecosystem gig roadmapping

### ISSUE THREAD

**Issue by serapath** [playproject-io/contracting#4]
# `@todo` :hammer_and_wrench:
* [ ] **tasks here are to be done by our team. partner(s) please skip and read `@info` section**
  * [x] create gig roadmap and list expected results and share a recorded screencast to explain it
    * `@output` :question: `record project brief screencast`
    * `@output`:factory: #49
  * [ ] introduce selected collaborator(s) to the project in all its details
    * `@input` :question: `chosen project partners assigned to issues`
    * `@input` :question: `record project brief screencast`
    * `@input`:factory: #49
    * `@output` :question: `partners briefed and assigned to issues`
  * [ ] work with collaborator during the gig towards expected results
    * `@input` :question: `partners briefed and assigned to issues`
    * `@input`:factory: #49
    * `@output` :question: `project results`
  * [ ] work and refine the roadmapping by adding and restructuring issues and assign them too
    * `@input` :question: `chosen project partners`
    * `@input`:factory: #49
    * `@input` :question: `project results`
    * `@output` :question: `final project results`
  * [ ] evaluate gig results and pay collaborator(s) to finish the gig
    * `@input` :question: `final project results`
    * `@output` :question: :checkered_flag: `finished project`

---
# `@info` :point_down:

The chosen collaborator(s) will get paid to execute the gig and make a themable website.

... more details will be announced at the end of the trial phase ...
