### ISSUE TITLE
Conceptual Design

### ISSUE THREAD

**Issue by CodeLawd** [playproject-io/contracting#40]
## `@todo`
 - [ ] Draw a flowchat of the webiste project (1 day)
    - `@input` :question: `dat ecosystem requirement document` from #39
    - `@output` :question: `Flowchart diagrams`
 - [ ] Create a low fidelity wireframe (sketches) (1 day)
    - `@input` :question: `Flowchart diagrams`
    - `@output` :question: `Document containing sketches of wireframe`
 - [ ] Manually prototype the website on paper (1 day)
    - `@input` :question: `Document containing sketches of wireframe`
    - `@output` :question: `Link to screencast prototype`
 - Next #41 

## `@info`
Conceptual design is an early phase of the design process, in which the broad outlines of function and form of something are articulated. It includes the design of interactions, experiences, processes.

**Comment by serapath** [comment]
**feedback `2022.04.28`**

a little type shows a standalone `:` which maybe should be removed, but otherwise

same as in https://github.com/playproject-io/contracting/issues/45#issuecomment-1112698703

**Comment by serapath** [comment]
merged into #49
