### ISSUE TITLE
UI Prototying

### ISSUE THREAD

**Issue by CodeLawd** [playproject-io/contracting#41]
## `@todo`
 - [ ] Create a mid fidelity wireframe (Balsamiq) (2 days)
   - `@input` :question: `Link to screencast prototype` from #40
   - `@output` :question: `Link to balsamiq design`
 - [ ] Create high fidelity wireframe (Figma) (10 days)
   - `@input` :question: `Link to balsamiq design`
   - `@output` :question: `Link to Figma design`
 - [ ] Create the design prototype for high fidelity wireframe (2 days)
   - `@input` :question: `Link to Figma design`
   - `@output` :question: `Link to screencast for the prototype`
 - Next #42 

## `@info`
A prototyping tool enables a designer to weave visuals, navigational elements, and interactions together to give a solid representation of how a design will behave and feel. It's an essential tool in any UI/UX designer's arsenal.

**Comment by serapath** [comment]
**feedback `2022.04.28`**

same as in https://github.com/playproject-io/contracting/issues/45#issuecomment-1112698703

also there is a specific `@output` listed that is not a final output but also doesnt have a `next` to show where it is used ...so you might want to update that too :-)

**Comment by serapath** [comment]
merged into #49
