### ISSUE TITLE
Deployment and Presentation

### ISSUE THREAD

**Issue by CodeLawd** [playproject-io/contracting#44]
## `@todo`
- [ ] Deploy website and record presentation (2 day)
   - [ ] Look for a situable hosting platform and compare prices
     * `@output` :question: `comparison table with best hosting options`
   - [ ] present options and choose winner
     * `@output` :question: `user/pass account with chosen hosting provider`
   - [ ] Deploy the webisite online to be accessible for use by the end users
     - `@input` :question: `implemented website repository` from #42
     - `@output` :question: :checkered_flag: `URL of the hosted website`
   - [ ] record a video screencast showing the full implemention of the website 🎏
     - `@output` :question: :checkered_flag: `recorded video on youtube`

## `@info`
- We would need to look for platforms where we can host the website
- Then compare them for prices and we choose the best plan
- Buy domain and deploy the website
- Record a video Screencast will be recorded to show the implementation of the dat ecosystem website is working.

**Comment by serapath** [comment]
**feedback `2022.04.28`**

same as in https://github.com/playproject-io/contracting/issues/45#issuecomment-1112698703


so for example again, the tasks could be

```
...

- [ ] deploy website and record presentation
   - [ ] Look for a situable hosting platform and compare prices
     * `@output` :question: `comparison table with best hosting options`
   - [ ] present options and choose winner
     * `@output` :question: `user/pass account with chosen hosting provider`
   - [ ] Deploy the webisite online to be accessible for use by the end users
     - `@input` :question: `implemented website repository` from #42
     - `@output` :question: :checkered_flag: `URL of the hosted website`
   - [ ] record a video screencast showing the full implemention of the website 🎏
     - `@output` :question: :checkered_flag: `recorded video on youtube`

...
```

not saying it needs to be exactly like the above, especially because we will just use github pages for hosting so we can skip that, as it is supposed to be a static website in the end :-) ...that uses javascript client side to `fetch(...)` or `websocket` whatever it needs, but formally the above needs to be improved regarding the form

**Comment by serapath** [comment]
merged into #49
