### ISSUE TITLE
User Research

### ISSUE THREAD

**Issue by CodeLawd** [playproject-io/contracting#45]
## `@todo`
 - [ ] `@input` ❓ : `User Interview`
 - [ ] `@input` :question: `Stakeholder's Interview`
 - [ ] `@input` :question: `Persona Creation`
 - [ ] `@input` :question: `User Task Flow`
 - [ ] `@input` :question: `User Stories`
- Next #46 
## `@info`
User research focuses on understanding user behaviors, needs, and motivations through interviews, surveys, usability evaluations and other forms of feedback methodologies. It is used to understand how people interact with products and evaluate whether design solutions meet their needs.

**Comment by serapath** [comment]
**feedback `2022.04.28`**

same as in other issues regarding the input/outputs shouldnt have checkboxes and need to be indented as sub bullet points to at least a single todo and `next` label can only be attached as sub bullet point to an actual output which is needed to justify doing a specific issue and its todos at all.

Of course, outputs are only "legit" if they are either final outputs of the project or inputs into other todos/issues that contribute towards the final output :-)
