### ISSUE TITLE
Features and Functionalities

### ISSUE THREAD

**Issue by CodeLawd** [playproject-io/contracting#46]
## `@todo`
- [ ] `@input` :factory:  [website section for organizing structure and processes](https://user-images.githubusercontent.com/1076427/145653435-34a1ad82-0512-4c20-84eb-317681bd4197.png) 
- [ ] `@input` :factory:  [dat-ecosystem garden application form](https://docs.google.com/forms/d/e/1FAIpQLSf9YxzVOTdPQKTwFoHzPTpSBNEm9dqOdYnZdP_bPAy4hrGQ0A/viewform)
- [ ] `@input` :factory: [Joining Rules](https://hackmd.io/5zL2Qt4_Sv6-_YgY8rJspg)
- [ ] `@input` :factory: [dat-ecosystem open collective account](https://opencollective.com/dat)
- Next #47 
## `@info`
This section defines the product we are about to build: It outlines the product's purpose, its features, functionalities, and behavior. Next, you share the PRD with (and seek input from) stakeholders - business and technical teams who will help build, launch or market your product.

**Comment by serapath** [comment]
**feedback `2022.04.28`**

same as in https://github.com/playproject-io/contracting/issues/45#issuecomment-1112698703

**Comment by serapath** [comment]
merged into #49
