### ISSUE TITLE
Competitive Analysis

### ISSUE THREAD

**Issue by CodeLawd** [playproject-io/contracting#47]
## `@todo`
- [ ] `@input` :question: `Identify competitors`
- [ ]  `@input` :question: `Analyze competitors' online presence`
- [ ] `@input` :question: `Check online reviews`
- [ ] `@input` :question: `Talk to competitors’ customers`
- [ ] `@input` :question: `Identify their strengths and weaknesses`
- [ ] `@input` :question: `Use research tools`
- Next #40 
## `@info`
A competitive analysis is a strategy that involves researching major competitors to gain insight into their products, sales, and marketing tactics. Implementing stronger business strategies, warding off competitors, and capturing market share are just a few benefits of conducting a competitive market analysis.

**Comment by serapath** [comment]
**feedback `2022.04.28`**

same feedback applies as [here](https://github.com/playproject-io/contracting/issues/48#issuecomment-1112679526)

and its mainly about:
1. the missing todo, e.g. `* [ ] competitive analysis`
2. the inputs have no checkbox
3. the planned output document is missing at the end of the list
4. only outputs have a `next` field, while inputs can have a `from` field if they were created in other issues as outputs
