### ISSUE TITLE
Web UI Refinement

### ISSUE THREAD

**Issue by CodeLawd** [playproject-io/contracting#48]
## `@todo`
 - [ ] Apply changes to the Web UI (3 days)
  - `@input` :question: `Link to usability test report` `from` #43 
  - `@output` :question: `Link to updated Website UI`
- Next #44 
## `@info`
Update changes based on input from Validation and Testing Phase

**Comment by serapath** [comment]
**feedback `2022.04.28`**

heya, so i think there is quite some fixing needed regarding the way we format our issues :sweat_smile: 

**alright, so in essence, the core idea of a plan is simple:**


1. its just todos issues and sub todos issues everywhere.


2. and each todo can list links to input and output documents for itself and those documents can be  :question: (=planned), or :factory: (=work in progress), or :package: (= done)


3. and finally, each output document has `next` fields to list all other issues where they are re-used as input with a `from` field that links back to the issue where the document was produced as an output.

...thats it. thats all, nothing more basically.


-------------------

**How does that apply to your issue above?**

1. todos always have a checkbox in front
2. inputs/outputs never have a checkbox in front

```
## `@todo`
 - [ ] `@input` :question: `If` #43 `fails, repeat the whole process from` #41
 - Next #44 
## `@info`
Perform iteration till all the validation passes
```
might rather be written like

```
## `@todo`
* [ ] perform initial iteration
  * `@input` :question: `Link to the high fidelity wireframe/prototyp` from #41
  * `@output` :question: `Link to refined high fidelity wireframe/prototyp`
  * [ ] refine high fidelity wireframe based on feedback
    * `@input` :question: `Link to refined high fidelity wireframe/prototyp`
    * `@output` :question: `Link to refined high fidelity wireframe/prototyp`
        * next #44

---

## `@info`
Perform iteration till all the validation passes

```

not exactly sure that is what you want, but iterating is more implicit, we don't do **if** or **loop** inside our issue system. This system is still for humans, which means the above has the same input and output for the "refine" todo, which means you just iterate or loop repeatedly to refine until things are great and then you mark the todo as done and move on to the next issue #44 :-)

**Comment by serapath** [comment]
merged into #49
