### ISSUE TITLE
project application

### ISSUE THREAD

**Issue by serapath** [playproject-io/contracting#5]
# `@todo`
* [x] tasks to be done by our team and not the applicants:
    * [x] wait for all applications until the weekend of the deadline `2022.02.18-23:00(UTC0)`
    * [x] watch all application videos received before locking the issue
    * [x] lock the issue comments during the weekend after the deadline passed
    * [x] evaluate submitted screencasts to choose candidate(s)
    * [x] inform and announce chosen candidate(s)
        * `@output` :package: [`MATTEONE`](https://github.com/playproject-io/contracting/issues/5#issuecomment-1100776157)
        * `@output` :package: [`Ayoola Daniel`](https://github.com/playproject-io/contracting/issues/5#issuecomment-1100776297)
        * `@output` :package: [`高梓棋 (taiwan)`](https://github.com/playproject-io/contracting/issues/5#issuecomment-1100776489)
        * `@output` :package: [`Judy Li`](https://github.com/playproject-io/contracting/issues/5#issuecomment-1100776574)
        * `@output` :package: [`0_0NoOB`](https://github.com/playproject-io/contracting/issues/5#issuecomment-1100776724)
        * `@output` :package: [`mimi.uxui`](https://github.com/playproject-io/contracting/issues/5#issuecomment-1100776803)
        * `@output` :package: [`MD Agency`](https://github.com/playproject-io/contracting/issues/5#issuecomment-1100776881)

---
# `@info`

## [2. click here to learn about the gig](https://github.com/playproject-io/contracting/issues/7)

---

### 1. post your candidate profile and portfolio, which needs to include:
  1. show your github and twitter profile (make one if you dont have one)
  2. present your portfolio with focus on your outstanding designs and wireframes
  3. (if any) show live apps or websites you made or worked on and what you did
  4. (if any) present github repos you made or worked on and what you did

**you can use one of these browser extensions to record the screencast:**
* e.g. screencastify
  * https://chrome.google.com/webstore/detail/screencastify-screen-vide/mmeijimgabbpbgpdklnllpncmdofkcpn?hl=en
* e.g. loom
  * https://chrome.google.com/webstore/detail/loom-%E2%80%93-free-screen-and-ca/liecbddmkiiihnedobmlmillhodjkdmb
* e.g. vidyard
  * https://chrome.google.com/webstore/detail/vidyard-free-video-and-sc/jiihcciniecimeajcniapbngjjbonjan?hl=en

### 3. we will carefully inspect and evaluate all submitted applications
1. we will watch your recorded screencast presentation
2. we will study all links you provide
3. we will discuss with our team
4. we will make a subjective decision to choose probably only a single candidate

**Comment by serapath** [comment]
### MATTEONE

#### Background:
> My background is comics and graffiti (>15y). I have a Wacom tablet and can draw digital. I also attend conferences like 36C3, RC3 and other ones the last 10 years. But I was not patient enough to learn programming yet. December last year I tried some PHP, MYSQL and JS. What are you looking for exactly?

> Hmmm. I am doing more analog work but can I also use digital tools. But to be honest the last time I used CSS was back in 2006... :/

**Comment by serapath** [comment]
### Ayoola Daniel

#### Background:
I write react and other languages. Including web technologies
Use Figma too
Can basically build out my designs easily
I write js
Got SEO experience too


**github** https://github.com/dalexz4
**dribbble** https://dribbble.com/geekydaniel
**website** https://ayoola-seo.company/
* twitter: https://twitter.com/theayooladaniel


#### Location:
lagos, nigeria

**Comment by serapath** [comment]
### 高梓棋 (taiwan)


#### Background:
I gave a grid work only use grid
My background maybe start with drawing and animation lottie and also uiux design and front-end

**github** https://github.com/queekao
**website** https://queekao.github.io/MY-CV/CV.html
  * https://queekao.github.io/Guideline/guideline.html

#### Location:
taiwan

**Comment by serapath** [comment]
### Judy Li

#### Background:
* https://github.com/judy50024
* https://judylisdesign.myportfolio.com/
I can do raw CSS with SCSS.

My background is generally in art and design, I do painting since my early age and studied jewellery design at universities, I’ve done some graphic design jobs and turned UIUX designer for this recent 2 years. 
From 2019 I started to take online courses to learn web development and programming languages, I’m currently focused on front end development and constantly learning.

I see, I’m relatively a beginner so JS frameworks are still pretty confusing to me, besides there are so many to choose
I just finished a frontend bootcamp by this month, am currently unemployed and do some freelancing from time to time.
I had a full-time remote work experience for a Japanese startup before, from 2020/2 to 2021/9 sadly they shut down the business, so I'm looking for my next job
if we can work together i can basically dedicate full time, are you in Europe time zone?

#### Location:
taiwan

**Comment by serapath** [comment]
### 0_0NoOB

#### Background:
I do have knowledge of CSS, HTML and Javascript I mostly code using the vanilla aspects of these languages with the exception of SASS but I can work in just CSS if it is required. I am adept in the Adobe CS package (Illustrator, Indesign and Photoshop) I also dabble in UI/UX using Figma, my prototyping on UI/UX is not the best since I am still getting use to components and such but I can still contribute if I am needed.

I had a look at the github link, and I realised I need more understanding on how to use github other than just browsing and/or copy, pasting from there really lol.

at the moment I am currently working on an ecommerce site for a family member, so once thats up I will hopefully try to make a more public appearence since most previous clients I had are just hush hush, also another reason I dont generally have portfolio pieces to show, in any case I will keep that all in mind! and if you are asking why I applied here while working on projects is because I have bills to pay and as of now this current project is going to be commission's base so until it''s up and running there wont be any terms of income.


github thing is somewhat confusing to me, I understand a simple make git repository and such but the whole pull and such isn't something I've used, I have done some tampering a few years back using vscode and git requests to install code from git repositories but it's been so long I forgot how that works,

I did get a graphic design diploma, my programming I was self taught and I have been doing this since 2015, but as a freelancer so I have always been on my own. I have a linkedin it's 

i am moderator of this design discord server for UX/UI (nirvana group):
it's somewhat more organised than the UI/UX channle since a few mods and I are actively removing spam or try to remove anything that can be considered suspicious. it doesn't appear extremely active, I guess it just hard since it's one of those looking for work and or 


* dribble: https://dribbble.com/0_0Nathan
* linkedin: https://www.linkedin.com/in/mypersonalspacedesigner/
* codepen: https://codepen.io/0_0Nathan
* take note the simple designs are CSS only interactions taking advantage of the Checkbox hack, no javascript I made them myself, at the time I didnt see anyone that ever made it so I was pretty proud of the designs mysel

Also Adobe designs what are you looking for specificially, my behance does have I think atleast 3 logo design concepts, I have done abit of product and logo designs, even Isometric designs if you want to see?

work samples:
* https://media.discordapp.net/attachments/928468374093180940/928671423441031258/MOTH-abstract.png
* https://cdn.discordapp.com/attachments/928468374093180940/928671776760795146/kissanime.png
* https://cdn.discordapp.com/attachments/928468374093180940/928671777050222672/GTC.png
* https://cdn.discordapp.com/attachments/928468374093180940/928671795068928010/The-Fireplace_final_logo_rounded.png
* https://cdn.discordapp.com/attachments/928468374093180940/928671836475109467/The-Fireplace_final_logo.png
* https://cdn.discordapp.com/attachments/928468374093180940/928672368308678706/Flowers.png
* https://cdn.discordapp.com/attachments/928468374093180940/928672368635838494/incompleteISO.png
* https://cdn.discordapp.com/attachments/928468374093180940/928672368853917746/discord-profile.png


#### Location:
south africa

**Comment by serapath** [comment]
### mimi.uxui


#### Background:
i'm a ux ui designer and a frontend developer, my portfolio is still a work in progress (will be done by 13th of January)
i've been using css since 2018 or 2017
i can play around with flexbox, make grid layouts and media queries also vanilla js
at some point you have to pass by css and vanilla js before jumping to react and css frameworks or sass
because they're the fundamentals and just core
regarding the job advert, i have all these skills and i happen to be proficient haha
i don't see a reason why i'm not a good fit for this

I had my Masters degree in Business Intelligence  in 2020, but along the way of achieving that I realised that it's not for me, I still want a career in IT but just not in that part of the industry, I want to do UX/UI design and coding, to become a UX Unicorn, but specialised in web 3 and blockchain type of industry, simply because it's an undiscovered field, existing and fast growing, nobody knows where it going to go and how far, which is very interesting for me

I worked before as a freelancer, doing mainly design and frontend, I worked as fullstack developer but I quit after 4 months because it was unfulfilling and it didn't align with my goals and career path, then shortly after that, I found a frontend offer, which where i'm still currently doing but i'm planning to quit very soon for the same reason that made me quit my fullstack position

Currently, I live in Algeria and planning to move to Canada in about 5-7 month to pursue a second masters degree in computer science and AI.

I'm still open to other masters but for now, that's what's looking interesting for me


* figma: https://www.figma.com/file/At27mskUUiz5SRFLLCTuOt/PORTFOLIO?node-id=0%3A1
* github: https://github.com/mimi-uxui-dev
* twitter: https://twitter.com/mimi_uxui
* 

#### Location:
algeria

**Comment by serapath** [comment]
### MD Agency

#### Background:
* linkedin: https://www.linkedin.com/in/donatien-migue/
* figma: https://www.figma.com/proto/ZyDJG3k42Knd8PAgc2u3it/Midjamo?node-id=301%3A2
* I also use Adobe suite
* CSS it's not a problem for me
I am a one person digital agency named MD Agency - sometimes i hire employees
* currently i have a client, but looking foe new clients
* can be full available between february to august
* can provide UX/UI Design service
* 
* mail:  donatien.migue@mdagency.tech
* pages
  * https://total-technics.com/
  * https://staging.beig3.com/en/
* behance: https://www.behance.net/miguedonatien
* dribbble: https://dribbble.com/MigueDonatien
* twitter: https://twitter.com/MigueTsawo
* github: https://github.com/migudonatien


#### Location:
unknown
