### ISSUE TITLE
trial phase

### ISSUE THREAD

**Issue by serapath** [playproject-io/contracting#6]
# `@todo`
* [x] tasks to be done by our team and not the chosen candidate(s):
  * [x] write trial phase description and share a recorded screencast to explain it
    * [x] write trial phase description in `@info` section below
        * `@output` :package: see `@info` section below 
    * [x] add links to describe the project
        * `@output` :package: see `@info` section below
  * [x] introduce chosen candidates to the trial phase tasks
  * [x] work with candidates during trial phase towards trial phase results
  * [x] evaluate trial phase results to choose partner(s)
  * [x] inform chosen partner(s) to proceed with the gig
    * `@output` :package: [`mimi_ui_ux`](https://github.com/playproject-io/contracting/issues/5#issuecomment-1100776803) from [comment](https://github.com/playproject-io/contracting/issues/6#issuecomment-1100778421)

---

# `@info`

## 1. trial phase tasks and expected results

<details>
<summary>

1. **all candidates need to study all materials and finish the trial tasks within 2 days**
    1. study https://playproject.io
    2. study https://datdot.org
2. challenge1 - write a report with detailed improvement/feedback for playproject + datdotorg
3. challenge2 - design wireframes and make a codepen with css for a made up basic crypto wallet

</summary>

### Challenge1
 check https://playproject.io/ and/or https://datdot.org/  and review the page or comment on it.
Given the direction the pages are in (theme/style), which is what we explicitly chose.
1. How would you name the style and the elements and what trends exist 
2. How well is the page technically executed?
3. Can you notice some mistakes or problems the page has?
4. If it was your task to take those pages and improve them to make them "perfect" and make them look and feel even better, what would you do and how would you approach it?
    * basically from the top of the head, without investing enormous amounts of time. Just from your experience and skills and what do you think you could do if that was your task.

### Challenge2
Reasonably time boxed.

 1. So the idea is to take an existing app called **"metamask"** (a cryptocurrency wallet) and make a simple minimalist wireframe with 5-10 view of the app and with a nice theme

2. Then choose one of a few mood boards prepared on pinterest and create a quick theme for the app in a style similar to the chosen moodboard.
    * https://www.pinterest.de/serapath/play3/
    * https://www.pinterest.de/ninabreznik/datdot/

3. Then choose the most interesting screen of that wireframe and create it in raw html/css (no frameworks) in a https://codepen.io/ :slight_smile: (just make a free account if you don't have one)
    1. using css properties to allow theming
    2. including some sort of css grid or flexbox
    3. maybe using some cool new css features (container queries) are one of many, just to show what people know.
    4. make it responsive of course :slight_smile:
    5. add cool animations/transitions to spice it up

4. Also, please use a browser plugin like (e.g. loom, screencastify, vidyard, etc...) to record 1-2 **short summary** screencasts between 5-10 minutes to explain the process (how you use your tools and skills to solve it) and the results
    * you can explain the results but also show part of the process of how you uses your tools (e.g. adobe, etc...) and raw CSS in codepen, to get those results :slight_smile:

If nothing else we hope this can be an interesting portfolio item even if you are not chosen in the end and.
 
So I guess all in all it should be about using adobe/figma/whatever.... to quickly make some wireframes and/or style guide with app components, including interesting colors/fonts/icons/elements and then code it with raw html/css without any css frameworks - but copy/paste and using online resources for inspiration or to get assets or whatever is cool. In the end it would be cool to have some really impressive result, but of course showing css skills and design knowledge matters a lot too

</details>

## 2. evaluation of trial phase
1. our team will then evaluate the results subjectively
4. our team will then subjectively choose partner(s) based on application and trial phase results
    * we will inform the chosen partner(s) to start working on the gig

**_We will probably only choose a single candidate but we might choose more than one candidate and then the chosen candidates will work in parallel together on the project_**

**Comment by serapath** [comment]
#### MATTEONE

#### Challenge1 - Feedback for playproject + datdotorg:
> I liked your designs on your webpage you forwarded. a bit to geometrical but great :)

#### Challenge2 - design wireframes + make one codepen with css:

**Comment by serapath** [comment]
### Ayoola Daniel

#### Challenge1 - Feedback for playproject + datdotorg:
https://imgur.com/s81FD0I.png
Basically I stick on the knowledge about design just make the basic feedback if you want more maybe you can give me some direction about the website then I can give more details and because now I just scratch from the surface I don't know about the core of the brand or the team...

#### Challenge2 - design wireframes + make one codepen with css:
---

**Comment by serapath** [comment]
### 高梓棋 (taiwan)

#### Challenge1 - Feedback for playproject + datdotorg:
#### Challenge2 - design wireframes + make one codepen with css:

**Comment by serapath** [comment]
### Judy Li


#### challenges:
A few questions,
Is the metamask one only needs 1 single page as well as RWD?
Can you take a screen shot of which page and please provide the Pinterest board.
A video is a bit tough for me though, cuz I always do things in fractal times and if so I’ll need to edit the video after.
Judy
Judy Li
Also what’s the deadline of this trial task?

#### Challenge1 - Feedback for playproject + datdotorg:


PlayProject
Pros:
1. Color is pretty fun and applies to its topic
2. Good picks for pictures
3. Contents are abundant and informative

Cons:
1. RWD is broken in several places, especially the navigation bar
2. The navigation is confusing, sitemap and information architecture adjustment needed
3. Hero carousel is inconsistent, font, size and layout are different, also it is too long(too many dots)
4. Lots of places are not displayed properly(eg. not centered)
5. Buttons are inconsistent, eg. hover state, padding, font


DatDot
Pros:
1. The retro style is pretty trendy also black and white color is safe
Cons:
1. There’s no RWD (but perhaps it’s not that necessary for documentation)
2. A few buttons are not consistent
3. Some pic’s resolution are low
4. The link to Twitter is “surprising”, considering add the social icon

more details about playproject + datdot feedback:
https://www.figma.com/file/JGbey8SLJJTET5QfZrGici/Untitled?node-id=0%3A1


#### Challenge2 - design wireframes + make one codepen with css:

**Comment by serapath** [comment]
### 0_0NoOB

#### Challenge1 - Feedback for playproject + datdotorg:
https://cdn.discordapp.com/attachments/928468374093180940/929485500723634267/review.pdf
and:
honestly it's harder to say anything about the datdot site, it's unique, yeah it doesn't have good support for responsiveness, but thats the same for most document based site, access to information is what's important about them, perhaps there are ways to make it responsive, but beyond that, the main focus or intent of the site is doing as intended 🙂

#### Challenge2 - design wireframes + make one codepen with css:
figma: https://www.figma.com/file/09mgASnjyWgsYCINSknXHQ/MetaMask_draft?node-id=0%3A1
codepen: https://codepen.io/0_0Nathan/pen/ExwOgKJ
video wireframes: https://www.loom.com/share/b814ef68ca674a3e9bdb014c2b6958d3?sharedAppSource=personal_library

**Comment by serapath** [comment]
### mimi.uxui


#### Challenge1 - Feedback for playproject + datdotorg:
https://cdn.discordapp.com/attachments/929011761754030200/929825521297137784/Thoughts.pdf

#### Challenge2 - design wireframes + make one codepen with css:
https://codepen.io/mimi-uxui-dev/full/VwMqqBv
https://www.figma.com/file/778zvchdLE36gEAhjsa0bw/Untitled?node-id=0%3A1
moodboard: I picked the one with the low poly shapes, but i couldn't ignore the look and feel of metamask, so it's kinda a combination of both haha
screenshots rather than screencasts:
* https://cdn.discordapp.com/attachments/929011761754030200/931556462352826378/20220114_153137.jpg
* https://cdn.discordapp.com/attachments/929011761754030200/931556669291384912/20220114_153214.jpg
*  i thought you wanted an explanation, that's what i wanted to do, something a like a tutorial haha, but my microphone doesnt work
* Redesign of the CTA  https://watch.screencastify.com/v/45BLeV3mqjhL9ok8pHUR
* Code of CTA 
https://watch.screencastify.com/v/6hN6d8Ovc7Fqt4qnH8Ha
https://watch.screencastify.com/v/N7riFDYsRy1ttj6wYoRs

**Comment by serapath** [comment]
### MD Agency

#### Challenge1 - Feedback for playproject + datdotorg:
 MD Agency: https://playproject.io/:  This website have a huge accessibility issues according to the color choise, typography and contrast. Assets not looks good. And It's difficult to know which text related to which information
[16:32] MD Agency: https://datdot.org/: There we have a good information architecture but the visual not looks good
[16:35] MD Agency: The first website need a huge UX/UI works to organise well information, make it more accessible.

#### Challenge2 - design wireframes + make one codepen with css:
https://www.figma.com/file/CGJbON0pYpDlnnsDGlSr3O/DatDot?node-id=0%3A1

https://github.com/moderndesignagency/test-datdot

**Comment by serapath** [comment]
# EVALUATION
**Chosen partners:**
* `@output` :package: [`mimi_ui_ux`](https://github.com/playproject-io/contracting/issues/5#issuecomment-1100776803)

---


#### MATTEONE
* `@output` :package: https://github.com/playproject-io/contracting/issues/6#issuecomment-1100777968

#### Evaluation:
CHALLENGES:
    * not enough information and input to consider this candidate
RESULT:
    * did not provide enough input to qualify
    
---

### Ayoola Daniel
* `@output` :package: https://github.com/playproject-io/contracting/issues/6#issuecomment-1100778089

#### Evaluation:
CHALLENGES:
    1. first challenge - ok review
        * amazing way of presenting the analysis (screenshot of website + annotations) is very pragmatic
        * sadly a bit hard to understand, because of more basic english 
    2. missing second challenge
OTHER:
    * Portfolio on github looks quite decent, but has only simple desings
    * dribble portfolio looks decent, but its not app wireframes, but mostly websites and/or landingpages
    * is active on social media and has online visibility/brand on twitter with 1.6k followers
RESULT:
  * our main focus is to find somebody with exceptional design skills and a broad variety of design tasks they can do
  * also good CSS skills are important
  * other skills are a nice bonus, but are secondary to what we are looking for


---

### 高梓棋 (taiwan)
* `@output` :package: https://github.com/playproject-io/contracting/issues/6#issuecomment-1100778139


#### Evaluation:
CHALLENGES:
    1. no solved challenges
OTHER:
  * very detailed and nice portfolio
  * seems can do a project from A to Z based on portfolio examples on website
RESULT:
  * did not seem interested by not solving any challenges


---

### Judy Li
* `@output` :package: https://github.com/playproject-io/contracting/issues/6#issuecomment-1100778205


#### Evaluation:
CHALLENGES:
    1. first challenge
      1. quite nice first and torough review (sadly our mistake was to give the wrong first website to analyze)
      2. ok review of second link
    3. second challenge is missing
OTHER:
    * amazing design skills
    * available full time
    * nice instagram drawings as an additional bonus
    * broad variety of different designs, styles, etc...
    * has a github profile
    * already familiar with NFTs and basics of crypto
    * lots of nice portfolio entries
    * portfoio page (cryptostal) is very slow when it loads and design is relatively basic
      * feeling for proportions, whitespace, and other design aspects seems to be missing onthis particular one
RESULT:
    * interesting candidate, would want to invite her to a video call interview :-)
  

---

### 0_0NoOB
* `@output` :package: https://github.com/playproject-io/contracting/issues/6#issuecomment-1100778251

#### Evaluation:
CHALLENGES:
    1. first challenge 
        1. did not review the design, but more the user experience, but still quite an interesting analysis with good points
        2. produced review as a PDF summary to easily share it with the team for review
    2. second challenge:
        1. can execute in under given time constraints
        2. can achieve effect with minimal effort based on the task specification
        3. design is based on mood board, but visual impression is average
OTHER:
    1. has good english, but expresses a bit verbose
    2. very openly communicating (+1) which is great
    3. public portfolio suggests more basic design skills
    4. no github or twitter account
RESULT:
    * very interesting candidate with lots of additional bonus skills
    * sadly design skills shown in portfolio are not too convincing for what we are looking for

---

### mimi.uxui
* `@output` :package: https://github.com/playproject-io/contracting/issues/6#issuecomment-1100778265

#### Evaluation:
CHALLENGES:
    1. first challenge
        1. most professionally executed challenge and systematic walk-through to all page elements + very good feedback points
    2. second challenge
        1. no wireframes of all the different screens
        2. the designs do not look too similar to the provided mood boards
OTHER:
    1. feels the most professional
    2. feels like a nice personality to communicate to and it seems it would be easy to work with her
    3. figma portfolio pages look highly professional and well executed, but relatively generic and mainstream designs
    4. has quite a few interesting github portfolio items and relatively recent activity
RESULT:
    * interesting candidate, would want to invite her to a video call interview :-)
    
---

### MD Agency
* `@output` :package: https://github.com/playproject-io/contracting/issues/6#issuecomment-1100778286

#### Evaluation:
CHALLENGES:
    1. first challenge
        1. very brief feedback with little to no explanation
    2. second challenge:
        1. good execution of the challenge
        2. design is in datdot style, but doesnt reflect the mood boards
        3. the animation doesnt seem to make sense (why would the whole UI slide in from the side?)
OTHER:
    * portfolio looks ok, but designs do not look exceptional
    * candidate knows some javascript, but thats only a bonus and not essential for what we are looking for
    * screen cast was 30 minutes, but not a conscise summary of whats essential
RESULT:
  * has a lot of extra skills which is a nice bonus
      * for example: knows javascript
  * the summary video is 30 minutes rather than a summary that is more to the point
  * the design seems to literally copy the datdot black/white design rather than moodboards
      * => so it feels like the design skills are not bad, but not good enough for our taste and what we are looking for
