### ISSUE TITLE
wizardamigos gig roadmapping

### ISSUE THREAD

**Issue by serapath** [playproject-io/contracting#7]
# `@todo` :hammer_and_wrench:
* [ ] **tasks here are to be done by our team. partner(s) please skip and read `@info` section**
  * [x] create gig roadmap and list expected results
    * `@output`:package: https://github.com/wizardamigos/wizardamigos.github.io/issues/38
  * [x] introduce selected collaborator(s) to the project in all its details
    * `@input` :package: [`chosen project partners assigned to issues`](https://github.com/playproject-io/contracting/issues/5#issuecomment-1100776803) from #5 
    * `@input`:package: https://github.com/wizardamigos/wizardamigos.github.io/issues/38
    * `@output` :package: [`partners briefed and assigned to issues`](https://github.com/wizardamigos/wizardamigos.github.io/issues/38)
  * [ ] work with collaborator during the gig towards expected results
    * `@input` :package:  [`partners briefed and assigned to issues`](https://github.com/wizardamigos/wizardamigos.github.io/issues/38)
    * `@input`:factory: https://github.com/wizardamigos/wizardamigos.github.io/issues/38
    * `@output` :question: `project results`
  * [ ] work and refine the roadmapping by adding and restructuring issues and assign them too
    * `@input` :package:  [`chosen project partners assigned to issues`](https://github.com/playproject-io/contracting/issues/5#issuecomment-1100776803) from #5 
    * `@input`:factory: https://github.com/wizardamigos/wizardamigos.github.io/issues/38
    * `@input` :question: `project results`
    * `@output` :question: `final project results`
  * [ ] evaluate gig results and pay collaborator(s) to finish the gig
    * `@input` :question: `final project results`
    * `@output` :question: :checkered_flag: `finished project`

---
# `@info`

All further details can be found in the issues linked above
